project:
  type: website

website:
  title: "ISS626-VAA"
  navbar:
    left:
      - text: "Hands-on Exercise"
        menu:
          - text: "Hands-on Exercise 1"
            href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html"
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
format:
  html:
    theme: morph
    css: styles.css
    toc: true
    
editor: visual

    