<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="yufanyou2025">
<meta name="dcterms.date" content="2026-09-10">

<title>Where are recorded road fatalities concentrated in Greater Bangkok? – ISS626-VAA</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-dark-5a1953863e1f72ef3b996ef827f01ca7.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-3d1a0dfd7272f207e7469f14fcf4c49a.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="../../styles.css">
<link rel="stylesheet" href="report.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="/index.html">
    <span class="navbar-title">ISS626-VAA</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-take-home-exercise" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Take-home Exercise</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-take-home-exercise">    
        <li>
    <a class="dropdown-item" href="/Take-home_Ex/Take-home_Ex01/technical-report.html">
 <span class="dropdown-text">Exercise 1: Technical Report</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="/Take-home_Ex/Take-home_Ex01/executive-summary.html">
 <span class="dropdown-text">Exercise 1: Executive Summary</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://github.com/yufanyou2025/ISS626-VAA">
 <span class="dropdown-text">GitHub repository</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-hands-on-exercise" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Hands-on Exercise</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-hands-on-exercise">    
        <li>
    <a class="dropdown-item" href="/Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01a.html">
 <span class="dropdown-text">Hands-on Exercise 1A: Geospatial Data Science</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="/Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01b.html">
 <span class="dropdown-text">Hands-on Exercise 1B: Thematic Mapping</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="/Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02a.html">
 <span class="dropdown-text">Hands-on Exercise 2A: First-order Point Patterns</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="/Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02b.html">
 <span class="dropdown-text">Hands-on Exercise 2B: Second-order Point Patterns</span></a>
  </li>  
    </ul>
  </li>
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="/index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="/about.html"> 
<span class="menu-text">About</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Report index</h2>
   
  <ul class="collapse">
  <li><a href="#introduction-and-research-question" id="toc-introduction-and-research-question" class="nav-link active" data-scroll-target="#introduction-and-research-question"><span class="header-section-number">1</span> Introduction and research question</a></li>
  <li><a href="#data-and-study-design" id="toc-data-and-study-design" class="nav-link" data-scroll-target="#data-and-study-design"><span class="header-section-number">2</span> Data and study design</a></li>
  <li><a href="#task-1-data-preparation-and-quality" id="toc-task-1-data-preparation-and-quality" class="nav-link" data-scroll-target="#task-1-data-preparation-and-quality"><span class="header-section-number">3</span> Task 1 — Data preparation and quality</a></li>
  <li><a href="#task-2-first-order-analysis" id="toc-task-2-first-order-analysis" class="nav-link" data-scroll-target="#task-2-first-order-analysis"><span class="header-section-number">4</span> Task 2 — First-order analysis</a></li>
  <li><a href="#task-3-second-order-analysis" id="toc-task-3-second-order-analysis" class="nav-link" data-scroll-target="#task-3-second-order-analysis"><span class="header-section-number">5</span> Task 3 — Second-order analysis</a></li>
  <li><a href="#task-4-integration-and-sensitivity" id="toc-task-4-integration-and-sensitivity" class="nav-link" data-scroll-target="#task-4-integration-and-sensitivity"><span class="header-section-number">6</span> Task 4 — Integration and sensitivity</a></li>
  <li><a href="#task-5-geovisualisation-and-communication" id="toc-task-5-geovisualisation-and-communication" class="nav-link" data-scroll-target="#task-5-geovisualisation-and-communication"><span class="header-section-number">7</span> Task 5 — Geovisualisation and communication</a></li>
  <li><a href="#task-6-public-safety-planning-and-management" id="toc-task-6-public-safety-planning-and-management" class="nav-link" data-scroll-target="#task-6-public-safety-planning-and-management"><span class="header-section-number">8</span> Task 6 — Public-safety planning and management</a></li>
  <li><a href="#limitations-and-conclusion" id="toc-limitations-and-conclusion" class="nav-link" data-scroll-target="#limitations-and-conclusion">Limitations and conclusion</a></li>
  <li><a href="#reproducibility" id="toc-reproducibility" class="nav-link" data-scroll-target="#reproducibility">Reproducibility</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Where are recorded road fatalities concentrated in Greater Bangkok?</h1>
<p class="subtitle lead">Take-home Exercise 1 · January–September 2024</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>yufanyou2025 </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">September 10, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<div class="report-actions">
<p><a href="../../Take-home_Ex/Take-home_Ex01/executive-summary.html" class="report-action primary-action">View executive summary ↗</a> <a href="https://github.com/yufanyou2025/ISS626-VAA/blob/master/Take-home_Ex/Take-home_Ex01/analysis.R" class="report-action">Explore source code ↗</a></p>
</div>
<div class="research-snapshot" aria-label="Study at a glance">
<div class="snapshot-item">
<p><span class="snapshot-label">STUDY SAMPLE</span></p>
<p><span class="snapshot-value">530</span></p>
<p>Located fatality records</p>
</div>
<div class="snapshot-item">
<p><span class="snapshot-label">SPATIAL COVERAGE</span></p>
<p><span class="snapshot-value">6</span></p>
<p>Greater Bangkok provinces</p>
</div>
<div class="snapshot-item">
<p><span class="snapshot-label">DATA LIMITATION</span></p>
<p><span class="snapshot-value">74.6%</span></p>
<p>National records missing coordinates</p>
</div>
</div>
<section id="introduction-and-research-question" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="introduction-and-research-question"><span class="header-section-number">1</span> Introduction and research question</h2>
<p>Road-safety planning needs to know where recorded deaths are concentrated, but a concentration on a map is not automatically evidence of greater individual risk. More journeys, more roads, and better reporting can all produce more observed events in an area.</p>
<p>This study asks: <strong>Where are geocoded fatality records concentrated in Greater Bangkok during January–September 2024, and how much evidence of clustering remains after allowing for spatially varying intensity?</strong></p>
<p>The distinction matters here. The spatially uniform reference is clearly rejected, while the intensity-adjusted curves are sensitive to how intensity is estimated. The defensible conclusion is that observed fatality locations are unevenly distributed. The analysis does not establish a stable pattern of interaction between distinct crashes.</p>
</section>
<section id="data-and-study-design" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="data-and-study-design"><span class="header-section-number">2</span> Data and study design</h2>
<section id="sources-and-observation-period" class="level3" data-number="2.1">
<h3 data-number="2.1" class="anchored" data-anchor-id="sources-and-observation-period"><span class="header-section-number">2.1</span> Sources and observation period</h3>
<p>The <a href="https://www.kaggle.com/datasets/pornsakkamchan/thailand-road-accident-fatalities-2024">Kaggle dataset</a>, uploaded by Pornsak Kamchan, is described as a Thailand Department of Disease Control compilation combining three sources. Version 1 was accessed on 10 September 2026; its metadata gives a last update of 5 January 2025. That provenance is the uploader’s description, not an independently verified linkage to the underlying source systems.</p>
<p>The original file contains <strong>12,762 rows and 13 fields</strong>. Although the title says 2024, every observed date lies between <strong>1 January and 30 September 2024</strong>. October–December are absent and are not treated as months with zero deaths. The date field is <strong>confirmed death date</strong>, so the monthly comparison is not a comparison of accident dates.</p>
<p>Administrative polygons come from <a href="https://www.geoboundaries.org/api/current/gbOpen/THA/ADM1/">geoBoundaries gbOpen Thailand ADM1</a>, boundary ID THA-ADM1-36821470. The pinned release uses source revision 9469f09, represents 2017, and was built in December 2023. Its sources are OpenStreetMap and Wambacher, under ODbL 1.0. Using an older boundary is a limitation; this study does not establish that every boundary matches 2024 exactly.</p>
</section>
<section id="event-definition" class="level3" data-number="2.2">
<h3 data-number="2.2" class="anchored" data-anchor-id="event-definition"><span class="header-section-number">2.2</span> Event definition</h3>
<p>One point represents <strong>one distinct record of a road-traffic fatality with usable coordinates inside the study area</strong>. It does not necessarily represent one distinct crash. There is no dedicated crash or person identifier.</p>
<p>Exactly identical rows are removed as likely duplicate records. This is a working assumption because different people could, in principle, share every released attribute. The 24 removed rows are outside the final metropolitan sample, so this choice does not change its 530 records. Repeated coordinates in that sample are retained: several fatalities can arise from one crash, and unrelated records may share a rounded location.</p>
<p>The sample contains <strong>503 distinct coordinate pairs</strong> and <strong>515 distinct location–date combinations</strong>. Collapsing coordinates is used only as a sensitivity check, not as a method for identifying unique crashes. No artificial jitter is added.</p>
</section>
<section id="spatial-window-and-crs" class="level3" data-number="2.3">
<h3 data-number="2.3" class="anchored" data-anchor-id="spatial-window-and-crs"><span class="header-section-number">2.3</span> Spatial window and CRS</h3>
<p>The window combines Bangkok, Samut Prakan, Nonthaburi, Pathum Thani, Nakhon Pathom, and Samut Sakhon. This follows the six-province “Bangkok and Vicinities” grouping in <a href="https://catalogapi.nso.go.th/api/doc/department/D10/SD10_04/SD10_04_265_1.pdf?preview=1">National Statistical Office documentation</a>. It provides an explicit administrative interpretation of Greater Bangkok.</p>
<p>The six polygons are selected using ISO codes TH-10, TH-11, TH-12, TH-13, TH-73, and TH-74 and dissolved into one study window. Its calculated area is <strong>7,604.1 km²</strong>. Spatial inclusion uses the coordinates, rather than the person’s province or province of death. Boundary intersections count as inside; no points in this file have ambiguous membership across the selected province polygons.</p>
<p>The coordinate headers are reversed in the downloaded file: all available values in <code>acc_lat</code> fall between approximately 97.9 and 105.6, while <code>acc_long</code> ranges from 5.9 to 20.4. These values and their Thailand locations support treating the former as longitude and the latter as latitude. WGS 84 is assumed for the original coordinates because the source does not document a datum. Coordinates and polygons are transformed to <strong>WGS 84 / UTM zone 47N, EPSG:32647</strong>, for metre-based distances and areas. Assigning a CRS and transforming coordinates are different operations; see the <a href="https://r-spatial.github.io/sf/articles/sf1.html">sf documentation</a>.</p>
</section>
<section id="main-analytical-choices" class="level3" data-number="2.4">
<h3 data-number="2.4" class="anchored" data-anchor-id="main-analytical-choices"><span class="header-section-number">2.4</span> Main analytical choices</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Choice</th>
<th>Setting and reason</th>
<th>Main limitation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Observation period</td>
<td>1 January–30 September 2024; complete available date span</td>
<td>Death dates, not crash times; completeness is unknown</td>
</tr>
<tr class="even">
<td>Observation space</td>
<td>Union of six administrative provinces</td>
<td>Road events occur on networks, not freely across all land</td>
</tr>
<tr class="odd">
<td>Kernel density</td>
<td>Gaussian, 3 km standard deviation; 500 m pixels</td>
<td>A regional display scale, not an optimal or causal scale</td>
</tr>
<tr class="even">
<td>Density sensitivity</td>
<td>1.5 km and 6 km, with the same legend</td>
<td>Apparent peaks depend on smoothing</td>
</tr>
<tr class="odd">
<td>Second-order function</td>
<td>Translation-corrected L(r) − r</td>
<td>Ordinary L assumes a stationary process</td>
</tr>
<tr class="even">
<td>Test distances</td>
<td>0.25–10 km in 50 m steps</td>
<td>Grid-based evidence; very short distances and longer scales excluded</td>
</tr>
<tr class="odd">
<td>Null model</td>
<td>Independent uniform locations, conditional on 530 points in the same window</td>
<td>Baseline of uniformity, not a realistic road-exposure model</td>
</tr>
<tr class="even">
<td>Monte Carlo settings</td>
<td>199 simulations; seed 20260910</td>
<td>Minimum attainable p-value is 0.005</td>
</tr>
<tr class="odd">
<td>Inhomogeneous diagnostic</td>
<td>Leave-one-out intensity; 3 km and 6 km bandwidths; translation correction; normalization power 2</td>
<td>Estimated intensity can make inverse weights unstable</td>
</tr>
<tr class="even">
<td>Coincidence sensitivity</td>
<td>One point per exact coordinate pair, 503 points</td>
<td>Changes the event unit and cannot recover crash IDs</td>
</tr>
</tbody>
</table>
<p>Ten kilometres is below one quarter of the window’s shorter bounding-box dimension, approximately 94 km. This limits, but does not remove, boundary influence. The 250 m lower limit avoids presenting very small distances as precise given the unknown coordinate accuracy.</p>
</section>
</section>
<section id="task-1-data-preparation-and-quality" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="task-1-data-preparation-and-quality"><span class="header-section-number">3</span> Task 1 — Data preparation and quality</h2>
<p>The workflow preserves the raw CSV and creates new longitude, latitude, and parsed date fields. UTF-8 import retains Thai values. The Buddhist Era year 2567 is converted to 2024 by subtracting 543; the day and month are retained. The script checks parsing, year values, coordinate ranges, polygon validity, and sample counts.</p>
<p>There are no parsing problems or invalid selected polygons in this run. Missing coordinates are not imputed. Text-based geocoding would introduce location uncertainty that is difficult to justify from the available metadata.</p>
<div class="cell">
<details class="code-fold">
<summary>Show R code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Complete AI-assisted worked analysis. See the declaration in the report.</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Run from the repository root: Rscript Take-home_Ex/Take-home_Ex01/analysis.R</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (.Platform<span class="sc">$</span>OS.type <span class="sc">==</span> <span class="st">"windows"</span>) {</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">invisible</span>(<span class="fu">Sys.setlocale</span>(<span class="st">"LC_CTYPE"</span>, <span class="st">"English_United States.utf8"</span>))</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>required <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"sf"</span>, <span class="st">"dplyr"</span>, <span class="st">"readr"</span>, <span class="st">"ggplot2"</span>, <span class="st">"spatstat.geom"</span>,</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>              <span class="st">"spatstat.explore"</span>, <span class="st">"spatstat.random"</span>, <span class="st">"jsonlite"</span>, <span class="st">"digest"</span>)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>missing_packages <span class="ot">&lt;-</span> required[<span class="sc">!</span><span class="fu">vapply</span>(required, requireNamespace, <span class="fu">logical</span>(<span class="dv">1</span>), <span class="at">quietly =</span> <span class="cn">TRUE</span>)]</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="fu">length</span>(missing_packages)) <span class="fu">stop</span>(<span class="st">"Install required packages: "</span>, <span class="fu">paste</span>(missing_packages, <span class="at">collapse =</span> <span class="st">", "</span>))</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="fu">suppressPackageStartupMessages</span>({</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">library</span>(sf); <span class="fu">library</span>(dplyr); <span class="fu">library</span>(ggplot2)</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">library</span>(spatstat.geom); <span class="fu">library</span>(spatstat.explore); <span class="fu">library</span>(spatstat.random)</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>base_dir <span class="ot">&lt;-</span> <span class="st">"Take-home_Ex/Take-home_Ex01"</span></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>fig_dir <span class="ot">&lt;-</span> <span class="fu">file.path</span>(base_dir, <span class="st">"figures"</span>)</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>out_dir <span class="ot">&lt;-</span> <span class="fu">file.path</span>(base_dir, <span class="st">"outputs"</span>)</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a><span class="fu">dir.create</span>(fig_dir, <span class="at">recursive =</span> <span class="cn">TRUE</span>, <span class="at">showWarnings =</span> <span class="cn">FALSE</span>)</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a><span class="fu">dir.create</span>(out_dir, <span class="at">recursive =</span> <span class="cn">TRUE</span>, <span class="at">showWarnings =</span> <span class="cn">FALSE</span>)</span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a>manifest <span class="ot">&lt;-</span> jsonlite<span class="sc">::</span><span class="fu">fromJSON</span>(<span class="fu">file.path</span>(base_dir, <span class="st">"notes/input-manifest.json"</span>))</span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="fu">seq_len</span>(<span class="fu">nrow</span>(manifest<span class="sc">$</span>files))) {</span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a>  file <span class="ot">&lt;-</span> <span class="fu">file.path</span>(base_dir, manifest<span class="sc">$</span>files<span class="sc">$</span>path[i])</span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (<span class="sc">!</span><span class="fu">file.exists</span>(file)) <span class="fu">stop</span>(<span class="st">"Missing original input: "</span>, file, <span class="st">"; see data/README.md"</span>)</span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stopifnot</span>(<span class="fu">identical</span>(digest<span class="sc">::</span><span class="fu">digest</span>(<span class="at">file =</span> file, <span class="at">algo =</span> <span class="st">"sha256"</span>), manifest<span class="sc">$</span>files<span class="sc">$</span>sha256[i]))</span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a><span class="fu">theme_set</span>(<span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">12</span>, <span class="at">base_family =</span> <span class="st">"sans"</span>) <span class="sc">+</span></span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">face =</span> <span class="st">"bold"</span>, <span class="at">colour =</span> <span class="st">"#20394f"</span>),</span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a>        <span class="at">plot.title.position =</span> <span class="st">"plot"</span>, <span class="at">plot.caption =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="dv">0</span>),</span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a>        <span class="at">panel.grid.minor =</span> <span class="fu">element_blank</span>(), <span class="at">legend.position =</span> <span class="st">"bottom"</span>))</span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a>save_plot <span class="ot">&lt;-</span> <span class="cf">function</span>(plot, filename, <span class="at">width =</span> <span class="dv">10</span>, <span class="at">height =</span> <span class="dv">6</span>) {</span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggsave</span>(<span class="fu">file.path</span>(fig_dir, filename), plot, <span class="at">width =</span> width, <span class="at">height =</span> height,</span>
<span id="cb1-31"><a href="#cb1-31" aria-hidden="true" tabindex="-1"></a>         <span class="at">dpi =</span> <span class="dv">180</span>, <span class="at">bg =</span> <span class="st">"white"</span>)</span>
<span id="cb1-32"><a href="#cb1-32" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<div class="cell">
<details class="code-fold">
<summary>Show R code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>raw <span class="ot">&lt;-</span> readr<span class="sc">::</span><span class="fu">read_csv</span>(<span class="fu">file.path</span>(base_dir, <span class="st">"data/raw/kaggle/thailand_road_accident_fatalities_2024.csv"</span>),</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>                      <span class="at">locale =</span> readr<span class="sc">::</span><span class="fu">locale</span>(<span class="at">encoding =</span> <span class="st">"UTF-8"</span>), <span class="at">show_col_types =</span> <span class="cn">FALSE</span>)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(<span class="fu">nrow</span>(raw) <span class="sc">==</span> <span class="dv">12762</span>L, <span class="fu">ncol</span>(raw) <span class="sc">==</span> <span class="dv">13</span>L, <span class="fu">nrow</span>(readr<span class="sc">::</span><span class="fu">problems</span>(raw)) <span class="sc">==</span> <span class="dv">0</span>L)</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>exact_duplicates <span class="ot">&lt;-</span> <span class="fu">sum</span>(<span class="fu">duplicated</span>(raw))</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>dat <span class="ot">&lt;-</span> <span class="fu">distinct</span>(raw)</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>parts <span class="ot">&lt;-</span> <span class="fu">do.call</span>(rbind, <span class="fu">strsplit</span>(dat<span class="sc">$</span>confirmed_death_date, <span class="st">"/"</span>, <span class="at">fixed =</span> <span class="cn">TRUE</span>))</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(<span class="fu">ncol</span>(parts) <span class="sc">==</span> <span class="dv">3</span>L, <span class="fu">all</span>(<span class="fu">as.integer</span>(parts[, <span class="dv">3</span>]) <span class="sc">==</span> <span class="dv">2567</span>L))</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>dat<span class="sc">$</span>death_date <span class="ot">&lt;-</span> <span class="fu">as.Date</span>(<span class="fu">sprintf</span>(<span class="st">"%04d-%02d-%02d"</span>, <span class="fu">as.integer</span>(parts[, <span class="dv">3</span>]) <span class="sc">-</span> <span class="dv">543</span>L,</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>                                  <span class="fu">as.integer</span>(parts[, <span class="dv">2</span>]), <span class="fu">as.integer</span>(parts[, <span class="dv">1</span>])))</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(<span class="sc">!</span><span class="fu">anyNA</span>(dat<span class="sc">$</span>death_date))</span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>period <span class="ot">&lt;-</span> dat <span class="sc">%&gt;%</span> <span class="fu">filter</span>(death_date <span class="sc">&gt;=</span> <span class="fu">as.Date</span>(<span class="st">"2024-01-01"</span>), death_date <span class="sc">&lt;=</span> <span class="fu">as.Date</span>(<span class="st">"2024-09-30"</span>))</span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a><span class="co"># All nonmissing values support this reversed header interpretation.</span></span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(<span class="fu">all</span>(<span class="fu">is.na</span>(period<span class="sc">$</span>acc_lat) <span class="sc">|</span> (period<span class="sc">$</span>acc_lat <span class="sc">&gt;=</span> <span class="dv">97</span> <span class="sc">&amp;</span> period<span class="sc">$</span>acc_lat <span class="sc">&lt;=</span> <span class="dv">106</span>)),</span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a>          <span class="fu">all</span>(<span class="fu">is.na</span>(period<span class="sc">$</span>acc_long) <span class="sc">|</span> (period<span class="sc">$</span>acc_long <span class="sc">&gt;=</span> <span class="dv">5</span> <span class="sc">&amp;</span> period<span class="sc">$</span>acc_long <span class="sc">&lt;=</span> <span class="dv">21</span>)))</span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a>period <span class="ot">&lt;-</span> period <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">longitude =</span> acc_lat, <span class="at">latitude =</span> acc_long,</span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a>                           <span class="at">has_coordinates =</span> <span class="fu">is.finite</span>(longitude) <span class="sc">&amp;</span> <span class="fu">is.finite</span>(latitude))</span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a>located <span class="ot">&lt;-</span> period <span class="sc">%&gt;%</span> <span class="fu">filter</span>(has_coordinates, <span class="fu">between</span>(longitude, <span class="sc">-</span><span class="dv">180</span>, <span class="dv">180</span>),</span>
<span id="cb2-18"><a href="#cb2-18" aria-hidden="true" tabindex="-1"></a>                            <span class="fu">between</span>(latitude, <span class="sc">-</span><span class="dv">90</span>, <span class="dv">90</span>))</span>
<span id="cb2-19"><a href="#cb2-19" aria-hidden="true" tabindex="-1"></a>points_ll <span class="ot">&lt;-</span> <span class="fu">st_as_sf</span>(located, <span class="at">coords =</span> <span class="fu">c</span>(<span class="st">"longitude"</span>, <span class="st">"latitude"</span>), <span class="at">crs =</span> <span class="dv">4326</span>, <span class="at">remove =</span> <span class="cn">FALSE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<div class="cell">
<details class="code-fold">
<summary>Show R code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>boundaries <span class="ot">&lt;-</span> <span class="fu">st_read</span>(<span class="fu">file.path</span>(base_dir, <span class="st">"data/raw/geoBoundaries-THA-ADM1.geojson"</span>), <span class="at">quiet =</span> <span class="cn">TRUE</span>)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>province_codes <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"TH-10"</span>, <span class="st">"TH-11"</span>, <span class="st">"TH-12"</span>, <span class="st">"TH-13"</span>, <span class="st">"TH-73"</span>, <span class="st">"TH-74"</span>)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>selected <span class="ot">&lt;-</span> boundaries[boundaries<span class="sc">$</span>shapeISO <span class="sc">%in%</span> province_codes, ]</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(<span class="fu">nrow</span>(selected) <span class="sc">==</span> <span class="dv">6</span>, <span class="sc">!</span><span class="fu">anyDuplicated</span>(selected<span class="sc">$</span>shapeISO))</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>invalid_boundaries <span class="ot">&lt;-</span> <span class="fu">sum</span>(<span class="sc">!</span><span class="fu">st_is_valid</span>(selected))</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>study <span class="ot">&lt;-</span> <span class="fu">st_transform</span>(<span class="fu">st_make_valid</span>(selected), <span class="dv">32647</span>)</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>study<span class="sc">$</span>province <span class="ot">&lt;-</span> <span class="fu">sub</span>(<span class="st">" Province$"</span>, <span class="st">""</span>, study<span class="sc">$</span>shapeName)</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>window_sf <span class="ot">&lt;-</span> <span class="fu">st_union</span>(study)</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>pts <span class="ot">&lt;-</span> <span class="fu">st_transform</span>(points_ll, <span class="dv">32647</span>)</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>membership <span class="ot">&lt;-</span> <span class="fu">st_intersects</span>(pts, window_sf)</span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>pts <span class="ot">&lt;-</span> pts[<span class="fu">lengths</span>(membership) <span class="sc">&gt;</span> <span class="dv">0</span>, ]</span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a>province_membership <span class="ot">&lt;-</span> <span class="fu">st_intersects</span>(pts, study)</span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a>ambiguous_boundaries <span class="ot">&lt;-</span> <span class="fu">sum</span>(<span class="fu">lengths</span>(province_membership) <span class="sc">!=</span> <span class="dv">1</span>L)</span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a><span class="co"># This input has no ambiguous province-boundary points; avoid double counting.</span></span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(ambiguous_boundaries <span class="sc">==</span> <span class="dv">0</span>L, <span class="fu">all</span>(<span class="fu">st_is_valid</span>(pts)))</span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a>pts<span class="sc">$</span>province <span class="ot">&lt;-</span> study<span class="sc">$</span>province[<span class="fu">vapply</span>(province_membership, <span class="st">`</span><span class="at">[</span><span class="st">`</span>, <span class="fu">integer</span>(<span class="dv">1</span>), <span class="dv">1</span>)]</span>
<span id="cb3-17"><a href="#cb3-17" aria-hidden="true" tabindex="-1"></a>xy <span class="ot">&lt;-</span> <span class="fu">st_coordinates</span>(pts)</span>
<span id="cb3-18"><a href="#cb3-18" aria-hidden="true" tabindex="-1"></a>W <span class="ot">&lt;-</span> <span class="fu">as.owin</span>(window_sf)</span>
<span id="cb3-19"><a href="#cb3-19" aria-hidden="true" tabindex="-1"></a>X <span class="ot">&lt;-</span> <span class="fu">ppp</span>(xy[, <span class="dv">1</span>], xy[, <span class="dv">2</span>], <span class="at">window =</span> W, <span class="at">checkdup =</span> <span class="cn">FALSE</span>)</span>
<span id="cb3-20"><a href="#cb3-20" aria-hidden="true" tabindex="-1"></a>X_unique <span class="ot">&lt;-</span> <span class="fu">ppp</span>(xy[<span class="sc">!</span><span class="fu">duplicated</span>(xy), <span class="dv">1</span>], xy[<span class="sc">!</span><span class="fu">duplicated</span>(xy), <span class="dv">2</span>], <span class="at">window =</span> W)</span>
<span id="cb3-21"><a href="#cb3-21" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(<span class="fu">npoints</span>(X) <span class="sc">==</span> <span class="fu">nrow</span>(pts), <span class="fu">npoints</span>(X) <span class="sc">==</span> <span class="dv">530</span>L)</span>
<span id="cb3-22"><a href="#cb3-22" aria-hidden="true" tabindex="-1"></a>area_km2 <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">st_area</span>(window_sf)) <span class="sc">/</span> <span class="fl">1e6</span></span>
<span id="cb3-23"><a href="#cb3-23" aria-hidden="true" tabindex="-1"></a>audit <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb3-24"><a href="#cb3-24" aria-hidden="true" tabindex="-1"></a>  <span class="at">stage =</span> <span class="fu">c</span>(<span class="st">"Original input"</span>, <span class="st">"Remove identical rows"</span>, <span class="st">"Valid dates in Jan-Sep 2024"</span>,</span>
<span id="cb3-25"><a href="#cb3-25" aria-hidden="true" tabindex="-1"></a>            <span class="st">"Usable coordinate pair"</span>, <span class="st">"Inside six-province window"</span>),</span>
<span id="cb3-26"><a href="#cb3-26" aria-hidden="true" tabindex="-1"></a>  <span class="at">retained =</span> <span class="fu">c</span>(<span class="fu">nrow</span>(raw), <span class="fu">nrow</span>(dat), <span class="fu">nrow</span>(period), <span class="fu">nrow</span>(located), <span class="fu">nrow</span>(pts)))</span>
<span id="cb3-27"><a href="#cb3-27" aria-hidden="true" tabindex="-1"></a>audit<span class="sc">$</span>removed <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">0</span>L, <span class="sc">-</span><span class="fu">diff</span>(audit<span class="sc">$</span>retained))</span>
<span id="cb3-28"><a href="#cb3-28" aria-hidden="true" tabindex="-1"></a>audit <span class="ot">&lt;-</span> audit[<span class="fu">c</span>(<span class="st">"stage"</span>, <span class="st">"removed"</span>, <span class="st">"retained"</span>)]</span>
<span id="cb3-29"><a href="#cb3-29" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(<span class="fu">sum</span>(audit<span class="sc">$</span>removed) <span class="sc">+</span> <span class="fu">tail</span>(audit<span class="sc">$</span>retained, <span class="dv">1</span>) <span class="sc">==</span> <span class="fu">nrow</span>(raw))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Sequential stage</th>
<th style="text-align: right;">Removed at this stage</th>
<th style="text-align: right;">Retained</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Original input</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">12,762</td>
</tr>
<tr class="even">
<td style="text-align: left;">Remove identical rows</td>
<td style="text-align: right;">24</td>
<td style="text-align: right;">12,738</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Valid dates in Jan-Sep 2024</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">12,738</td>
</tr>
<tr class="even">
<td style="text-align: left;">Usable coordinate pair</td>
<td style="text-align: right;">9,498</td>
<td style="text-align: right;">3,240</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Inside six-province window</td>
<td style="text-align: right;">2,710</td>
<td style="text-align: right;">530</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The sequence reconciles: 24 identical rows, 9,498 records without usable coordinates, and 2,710 located records outside the window are removed from the 12,762 input rows. The result is 530 spatial records. The largest loss occurs before spatial filtering: <strong>74.6% of distinct national records lack coordinates</strong>. This prevents the mapped sample from being treated as representative without further evidence.</p>
<section id="location-availability-by-province-of-death" class="level3" data-number="3.1">
<h3 data-number="3.1" class="anchored" data-anchor-id="location-availability-by-province-of-death"><span class="header-section-number">3.1</span> Location availability by province of death</h3>
<div id="fig-coverage" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-coverage-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figures/coverage.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-coverage-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Location availability among records labelled with each province of death.
</figcaption>
</figure>
</div>
<div id="interpretation-coverage">
<p>Coordinate availability varies from 25.7% for records labelled Nakhon Pathom to 45.5% for those labelled Bangkok. This difference warns against comparing mapped counts as if observation coverage were equal. The denominator here is each group defined by province of death; it is not the set of fatalities spatially located inside each polygon. Province of death and accident location can differ, so these percentages cannot be used directly to inflate the spatial counts.</p>
</div>
</section>
<section id="spatial-sample" class="level3" data-number="3.2">
<h3 data-number="3.2" class="anchored" data-anchor-id="spatial-sample"><span class="header-section-number">3.2</span> Spatial sample</h3>
<div id="fig-study" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-study-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figures/study-area.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-study-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Study window and located fatality records.
</figcaption>
</figure>
</div>
<div id="interpretation-study">
<p>Bangkok contains 232 of the 530 spatially selected records, or 43.8%. Records also extend into all five neighbouring provinces. This is a regional pattern rather than a set confined to the Bangkok administrative boundary. Points overlap where records share coordinates, and labels can obscure individual points. The figure shows the available geocoded sample; it neither locates missing records nor establishes the risk faced by road users.</p>
</div>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Province</th>
<th style="text-align: right;">Area (km²)</th>
<th style="text-align: right;">Located records</th>
<th style="text-align: right;">Records / km²</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Bangkok</td>
<td style="text-align: right;">1570.7</td>
<td style="text-align: right;">232</td>
<td style="text-align: right;">0.148</td>
</tr>
<tr class="even">
<td style="text-align: left;">Nakhon Pathom</td>
<td style="text-align: right;">2088.5</td>
<td style="text-align: right;">53</td>
<td style="text-align: right;">0.025</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Nonthaburi</td>
<td style="text-align: right;">639.0</td>
<td style="text-align: right;">54</td>
<td style="text-align: right;">0.085</td>
</tr>
<tr class="even">
<td style="text-align: left;">Pathum Thani</td>
<td style="text-align: right;">1513.6</td>
<td style="text-align: right;">81</td>
<td style="text-align: right;">0.054</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Samut Sakhon</td>
<td style="text-align: right;">839.4</td>
<td style="text-align: right;">40</td>
<td style="text-align: right;">0.048</td>
</tr>
<tr class="even">
<td style="text-align: left;">Samut Prakan</td>
<td style="text-align: right;">952.9</td>
<td style="text-align: right;">70</td>
<td style="text-align: right;">0.073</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Records per km² describe areal intensity over this nine-month extract. They are not deaths per person, per vehicle, or per kilometre travelled.</p>
<div class="cell">
<details class="code-fold">
<summary>Show R code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>thai_names <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"\u0e01\u0e23\u0e38\u0e07\u0e40\u0e17\u0e1e\u0e21\u0e2b\u0e32\u0e19\u0e04\u0e23"</span>,</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>                <span class="st">"\u0e2a\u0e21\u0e38\u0e17\u0e23\u0e1b\u0e23\u0e32\u0e01\u0e32\u0e23"</span>,</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>                <span class="st">"\u0e19\u0e19\u0e17\u0e1a\u0e38\u0e23\u0e35"</span>,</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>                <span class="st">"\u0e1b\u0e17\u0e38\u0e21\u0e18\u0e32\u0e19\u0e35"</span>,</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>                <span class="st">"\u0e19\u0e04\u0e23\u0e1b\u0e10\u0e21"</span>,</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>                <span class="st">"\u0e2a\u0e21\u0e38\u0e17\u0e23\u0e2a\u0e32\u0e04\u0e23"</span>)</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>name_lookup <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">province_of_death =</span> thai_names,</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>                         <span class="at">province =</span> <span class="fu">c</span>(<span class="st">"Bangkok"</span>, <span class="st">"Samut Prakan"</span>, <span class="st">"Nonthaburi"</span>, <span class="st">"Pathum Thani"</span>, <span class="st">"Nakhon Pathom"</span>, <span class="st">"Samut Sakhon"</span>))</span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>coverage <span class="ot">&lt;-</span> period <span class="sc">%&gt;%</span> <span class="fu">inner_join</span>(name_lookup, <span class="at">by =</span> <span class="st">"province_of_death"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(province) <span class="sc">%&gt;%</span> <span class="fu">summarise</span>(<span class="at">records =</span> <span class="fu">n</span>(), <span class="at">located =</span> <span class="fu">sum</span>(has_coordinates), <span class="at">.groups =</span> <span class="st">"drop"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">coverage_pct =</span> <span class="dv">100</span> <span class="sc">*</span> located <span class="sc">/</span> records)</span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a>counts <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(<span class="fu">table</span>(pts<span class="sc">$</span>province), <span class="at">stringsAsFactors =</span> <span class="cn">FALSE</span>)</span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(counts) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"province"</span>, <span class="st">"mapped_records"</span>)</span>
<span id="cb4-14"><a href="#cb4-14" aria-hidden="true" tabindex="-1"></a>province_table <span class="ot">&lt;-</span> study <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">area_km2 =</span> <span class="fu">as.numeric</span>(<span class="fu">st_area</span>(geometry)) <span class="sc">/</span> <span class="fl">1e6</span>) <span class="sc">%&gt;%</span></span>
<span id="cb4-15"><a href="#cb4-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_drop_geometry</span>() <span class="sc">%&gt;%</span> <span class="fu">select</span>(province, area_km2) <span class="sc">%&gt;%</span> <span class="fu">left_join</span>(counts, <span class="at">by =</span> <span class="st">"province"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb4-16"><a href="#cb4-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">records_per_km2 =</span> mapped_records <span class="sc">/</span> area_km2)</span>
<span id="cb4-17"><a href="#cb4-17" aria-hidden="true" tabindex="-1"></a>monthly <span class="ot">&lt;-</span> <span class="fu">st_drop_geometry</span>(pts) <span class="sc">%&gt;%</span> <span class="fu">count</span>(<span class="at">month =</span> <span class="fu">format</span>(death_date, <span class="st">"%m"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb4-18"><a href="#cb4-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">month =</span> <span class="fu">factor</span>(month, <span class="at">levels =</span> <span class="fu">sprintf</span>(<span class="st">"%02d"</span>, <span class="dv">1</span><span class="sc">:</span><span class="dv">9</span>), <span class="at">labels =</span> month.abb[<span class="dv">1</span><span class="sc">:</span><span class="dv">9</span>]))</span>
<span id="cb4-19"><a href="#cb4-19" aria-hidden="true" tabindex="-1"></a>coverage_plot <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(coverage, <span class="fu">aes</span>(<span class="fu">reorder</span>(province, coverage_pct), coverage_pct)) <span class="sc">+</span></span>
<span id="cb4-20"><a href="#cb4-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>(<span class="at">fill =</span> <span class="st">"#176f82"</span>, <span class="at">width =</span> <span class="fl">0.65</span>) <span class="sc">+</span></span>
<span id="cb4-21"><a href="#cb4-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> <span class="fu">sprintf</span>(<span class="st">"%.1f%%  (%d/%d)"</span>, coverage_pct, located, records)),</span>
<span id="cb4-22"><a href="#cb4-22" aria-hidden="true" tabindex="-1"></a>            <span class="at">hjust =</span> <span class="sc">-</span><span class="fl">0.1</span>, <span class="at">size =</span> <span class="fl">3.6</span>) <span class="sc">+</span> <span class="fu">coord_flip</span>(<span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">70</span>)) <span class="sc">+</span></span>
<span id="cb4-23"><a href="#cb4-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Location availability differs between death-province groups"</span>,</span>
<span id="cb4-24"><a href="#cb4-24" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"Denominator: records labelled with each province of death, after exact-row deduplication"</span>,</span>
<span id="cb4-25"><a href="#cb4-25" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="cn">NULL</span>, <span class="at">y =</span> <span class="st">"Records with coordinates (%)"</span>,</span>
<span id="cb4-26"><a href="#cb4-26" aria-hidden="true" tabindex="-1"></a>       <span class="at">caption =</span> <span class="st">"These groups do not define the spatial sample; coordinates determine inclusion in the study window.</span><span class="sc">\n</span><span class="st">Source: Kaggle / Thailand DDC compilation, January-September 2024."</span>)</span>
<span id="cb4-27"><a href="#cb4-27" aria-hidden="true" tabindex="-1"></a><span class="fu">save_plot</span>(coverage_plot, <span class="st">"coverage.png"</span>)</span>
<span id="cb4-28"><a href="#cb4-28" aria-hidden="true" tabindex="-1"></a>label_points <span class="ot">&lt;-</span> <span class="fu">suppressWarnings</span>(<span class="fu">st_point_on_surface</span>(study))</span>
<span id="cb4-29"><a href="#cb4-29" aria-hidden="true" tabindex="-1"></a>label_xy <span class="ot">&lt;-</span> <span class="fu">st_coordinates</span>(label_points)</span>
<span id="cb4-30"><a href="#cb4-30" aria-hidden="true" tabindex="-1"></a>labels <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">province =</span> study<span class="sc">$</span>province, <span class="at">x =</span> label_xy[,<span class="dv">1</span>], <span class="at">y =</span> label_xy[,<span class="dv">2</span>])</span>
<span id="cb4-31"><a href="#cb4-31" aria-hidden="true" tabindex="-1"></a>study_plot <span class="ot">&lt;-</span> <span class="fu">ggplot</span>() <span class="sc">+</span> <span class="fu">geom_sf</span>(<span class="at">data =</span> study, <span class="at">fill =</span> <span class="st">"#eef1f3"</span>, <span class="at">colour =</span> <span class="st">"#788a98"</span>, <span class="at">linewidth =</span> <span class="fl">0.4</span>) <span class="sc">+</span></span>
<span id="cb4-32"><a href="#cb4-32" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_sf</span>(<span class="at">data =</span> pts, <span class="at">colour =</span> <span class="st">"#b34a31"</span>, <span class="at">size =</span> <span class="fl">1.0</span>, <span class="at">alpha =</span> <span class="fl">0.6</span>) <span class="sc">+</span></span>
<span id="cb4-33"><a href="#cb4-33" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_label</span>(<span class="at">data =</span> labels, <span class="fu">aes</span>(x, y, <span class="at">label =</span> province), <span class="at">size =</span> <span class="fl">3.1</span>, <span class="at">fill =</span> <span class="st">"white"</span>, <span class="at">alpha =</span> <span class="fl">0.85</span>) <span class="sc">+</span></span>
<span id="cb4-34"><a href="#cb4-34" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_sf</span>(<span class="at">crs =</span> <span class="fu">st_crs</span>(<span class="dv">32647</span>), <span class="at">datum =</span> <span class="fu">st_crs</span>(<span class="dv">4326</span>)) <span class="sc">+</span></span>
<span id="cb4-35"><a href="#cb4-35" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"530 located fatality records in Bangkok and five neighbouring provinces"</span>,</span>
<span id="cb4-36"><a href="#cb4-36" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"Recorded death dates: January-September 2024 · points can overlap"</span>,</span>
<span id="cb4-37"><a href="#cb4-37" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Longitude"</span>, <span class="at">y =</span> <span class="st">"Latitude"</span>,</span>
<span id="cb4-38"><a href="#cb4-38" aria-hidden="true" tabindex="-1"></a>       <span class="at">caption =</span> <span class="st">"Analysis CRS: WGS 84 / UTM zone 47N (metres).</span><span class="sc">\n</span><span class="st">Sources: Kaggle / DDC compilation; geoBoundaries (OpenStreetMap, Wambacher; ODbL 1.0)."</span>)</span>
<span id="cb4-39"><a href="#cb4-39" aria-hidden="true" tabindex="-1"></a><span class="fu">save_plot</span>(study_plot, <span class="st">"study-area.png"</span>, <span class="at">height =</span> <span class="dv">7</span>)</span>
<span id="cb4-40"><a href="#cb4-40" aria-hidden="true" tabindex="-1"></a>monthly_plot <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(monthly, <span class="fu">aes</span>(month, n)) <span class="sc">+</span> <span class="fu">geom_col</span>(<span class="at">fill =</span> <span class="st">"#176f82"</span>, <span class="at">width =</span> <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb4-41"><a href="#cb4-41" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> n), <span class="at">vjust =</span> <span class="sc">-</span><span class="fl">0.45</span>, <span class="at">size =</span> <span class="dv">4</span>) <span class="sc">+</span> <span class="fu">expand_limits</span>(<span class="at">y =</span> <span class="fu">max</span>(monthly<span class="sc">$</span>n) <span class="sc">*</span> <span class="fl">1.13</span>) <span class="sc">+</span></span>
<span id="cb4-42"><a href="#cb4-42" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Monthly counts follow confirmed-death dates"</span>,</span>
<span id="cb4-43"><a href="#cb4-43" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"Located records inside the six-province window; October-December are absent from the input"</span>,</span>
<span id="cb4-44"><a href="#cb4-44" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="cn">NULL</span>, <span class="at">y =</span> <span class="st">"Located fatality records"</span>,</span>
<span id="cb4-45"><a href="#cb4-45" aria-hidden="true" tabindex="-1"></a>       <span class="at">caption =</span> <span class="st">"These are counts, not exposure-adjusted rates or accident-date totals. Source: Kaggle / DDC compilation."</span>)</span>
<span id="cb4-46"><a href="#cb4-46" aria-hidden="true" tabindex="-1"></a><span class="fu">save_plot</span>(monthly_plot, <span class="st">"monthly.png"</span>, <span class="at">height =</span> <span class="dv">5</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
</section>
</section>
<section id="task-2-first-order-analysis" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="task-2-first-order-analysis"><span class="header-section-number">4</span> Task 2 — First-order analysis</h2>
<section id="monthly-distribution" class="level3" data-number="4.1">
<h3 data-number="4.1" class="anchored" data-anchor-id="monthly-distribution"><span class="header-section-number">4.1</span> Monthly distribution</h3>
<div id="fig-monthly" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-monthly-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figures/monthly.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-monthly-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: Monthly counts using confirmed-death dates.
</figcaption>
</figure>
</div>
<div id="interpretation-monthly">
<p>January has the highest count in the spatial sample, with 78 records, and August has the lowest, with 43. September rises to 51. These differences describe the available death-date records, not changes in crash risk. The extract covers only nine months, the months differ in length, and coordinate availability may also change over time. A seasonal or holiday explanation would therefore need additional evidence.</p>
</div>
</section>
<section id="kernel-density-estimation" class="level3" data-number="4.2">
<h3 data-number="4.2" class="anchored" data-anchor-id="kernel-density-estimation"><span class="header-section-number">4.2</span> Kernel density estimation</h3>
<p>Gaussian kernel density estimation distributes each event over nearby locations. The 3 km bandwidth provides a district-scale view, while 1.5 km and 6 km show how much the map depends on smoothing. This is a transparent descriptive choice rather than a claim that 3 km is statistically optimal.</p>
<p>Edge correction compensates for kernel mass outside the observation window. All maps use 500 m pixels and one square-root colour scale, with legend values expressed in records per km². The units refer to the entire observed period and are not annualised. Tiny negative values from numerical FFT rounding are checked and clipped to zero for display.</p>
<div id="fig-kde" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-kde-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figures/kde-bandwidths.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-kde-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4: Kernel density with 1.5 km, 3 km, and 6 km bandwidths.
</figcaption>
</figure>
</div>
<div id="interpretation-kde">
<p>All three maps show a broad concentration in and around Bangkok, but the smaller bandwidth separates it into many local peaks. The maximum intensity falls from 0.545 records/km² at 1.5 km to 0.339 at 3 km and 0.257 at 6 km. The 3 km maximum lies within Bangkok. These are smoothed concentrations of recorded fatalities. Their positions and heights do not identify the most dangerous road segments, because traffic exposure, the road network, and missing records are not included.</p>
</div>
<p>The whole-window average is 0.070 records/km². The KDE is useful because that single average hides local variation. However, a planar kernel can smooth across rivers, inaccessible land, and neighbouring roads. A road-network interpretation would require additional data and different distance assumptions. The <a href="https://spatstat.org/">spatstat documentation</a> describes the package’s point-pattern framework.</p>
<div class="cell">
<details class="code-fold">
<summary>Show R code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Fixed district-scale smoothing, assessed at half and double bandwidth.</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>bandwidths <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1500</span>, <span class="dv">3000</span>, <span class="dv">6000</span>)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>kde_images <span class="ot">&lt;-</span> <span class="fu">lapply</span>(bandwidths, <span class="cf">function</span>(h) <span class="fu">density</span>(X, <span class="at">sigma =</span> h, <span class="at">edge =</span> <span class="cn">TRUE</span>, <span class="at">eps =</span> <span class="dv">500</span>))</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>kde_frames <span class="ot">&lt;-</span> <span class="fu">lapply</span>(<span class="fu">seq_along</span>(bandwidths), <span class="cf">function</span>(i) {</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>  frame <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(kde_images[[i]])</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>  <span class="co"># FFT smoothing can produce tiny negative round-off values in empty pixels.</span></span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stopifnot</span>(<span class="fu">min</span>(frame<span class="sc">$</span>value, <span class="at">na.rm =</span> <span class="cn">TRUE</span>) <span class="sc">&gt;</span> <span class="sc">-</span><span class="fl">1e-10</span>)</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>  frame<span class="sc">$</span>intensity <span class="ot">&lt;-</span> <span class="fu">pmax</span>(frame<span class="sc">$</span>value, <span class="dv">0</span>) <span class="sc">*</span> <span class="fl">1e6</span></span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>  frame<span class="sc">$</span>bandwidth <span class="ot">&lt;-</span> <span class="fu">paste0</span>(bandwidths[i] <span class="sc">/</span> <span class="dv">1000</span>, <span class="st">" km"</span>)</span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>  frame</span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a>kde_all <span class="ot">&lt;-</span> <span class="fu">bind_rows</span>(kde_frames)</span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a>kde_all<span class="sc">$</span>bandwidth <span class="ot">&lt;-</span> <span class="fu">factor</span>(kde_all<span class="sc">$</span>bandwidth, <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"1.5 km"</span>, <span class="st">"3 km"</span>, <span class="st">"6 km"</span>))</span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a>kde_plot <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(kde_all, <span class="fu">aes</span>(x, y, <span class="at">fill =</span> intensity)) <span class="sc">+</span> <span class="fu">geom_raster</span>() <span class="sc">+</span></span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_sf</span>(<span class="at">data =</span> study, <span class="at">fill =</span> <span class="cn">NA</span>, <span class="at">colour =</span> <span class="st">"#53616b"</span>, <span class="at">linewidth =</span> <span class="fl">0.25</span>, <span class="at">inherit.aes =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb5-16"><a href="#cb5-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>bandwidth, <span class="at">nrow =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb5-17"><a href="#cb5-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_viridis_c</span>(<span class="at">option =</span> <span class="st">"C"</span>, <span class="at">trans =</span> <span class="st">"sqrt"</span>, <span class="at">breaks =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="fl">0.1</span>, <span class="fl">0.3</span>, <span class="fl">0.5</span>),</span>
<span id="cb5-18"><a href="#cb5-18" aria-hidden="true" tabindex="-1"></a>                      <span class="at">name =</span> <span class="st">"Records / km² (square-root scale)"</span>,</span>
<span id="cb5-19"><a href="#cb5-19" aria-hidden="true" tabindex="-1"></a>                      <span class="at">guide =</span> <span class="fu">guide_colourbar</span>(<span class="at">barwidth =</span> grid<span class="sc">::</span><span class="fu">unit</span>(<span class="dv">9</span>, <span class="st">"cm"</span>),</span>
<span id="cb5-20"><a href="#cb5-20" aria-hidden="true" tabindex="-1"></a>                                              <span class="at">barheight =</span> grid<span class="sc">::</span><span class="fu">unit</span>(<span class="fl">0.35</span>, <span class="st">"cm"</span>), <span class="at">title.position =</span> <span class="st">"top"</span>)) <span class="sc">+</span></span>
<span id="cb5-21"><a href="#cb5-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_sf</span>(<span class="at">crs =</span> <span class="fu">st_crs</span>(<span class="dv">32647</span>), <span class="at">datum =</span> <span class="cn">NA</span>) <span class="sc">+</span></span>
<span id="cb5-22"><a href="#cb5-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text =</span> <span class="fu">element_blank</span>(), <span class="at">axis.ticks =</span> <span class="fu">element_blank</span>(), <span class="at">panel.grid =</span> <span class="fu">element_blank</span>()) <span class="sc">+</span></span>
<span id="cb5-23"><a href="#cb5-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Smoothing changes the apparent size and height of concentrations"</span>,</span>
<span id="cb5-24"><a href="#cb5-24" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"Gaussian kernel density · bandwidth is the kernel standard deviation · one shared colour scale"</span>,</span>
<span id="cb5-25"><a href="#cb5-25" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="cn">NULL</span>, <span class="at">y =</span> <span class="cn">NULL</span>,</span>
<span id="cb5-26"><a href="#cb5-26" aria-hidden="true" tabindex="-1"></a>       <span class="at">caption =</span> <span class="st">"500 m raster grid; edge-corrected event intensity for the observed nine-month period.</span><span class="sc">\n</span><span class="st">Sources: Kaggle / DDC; geoBoundaries (OSM, Wambacher; ODbL 1.0)."</span>)</span>
<span id="cb5-27"><a href="#cb5-27" aria-hidden="true" tabindex="-1"></a><span class="fu">save_plot</span>(kde_plot, <span class="st">"kde-bandwidths.png"</span>, <span class="at">width =</span> <span class="dv">13</span>, <span class="at">height =</span> <span class="dv">6</span>)</span>
<span id="cb5-28"><a href="#cb5-28" aria-hidden="true" tabindex="-1"></a>peak <span class="ot">&lt;-</span> kde_frames[[<span class="dv">2</span>]][<span class="fu">which.max</span>(kde_frames[[<span class="dv">2</span>]]<span class="sc">$</span>intensity), ]</span>
<span id="cb5-29"><a href="#cb5-29" aria-hidden="true" tabindex="-1"></a>peak_sf <span class="ot">&lt;-</span> <span class="fu">st_as_sf</span>(peak, <span class="at">coords =</span> <span class="fu">c</span>(<span class="st">"x"</span>, <span class="st">"y"</span>), <span class="at">crs =</span> <span class="dv">32647</span>)</span>
<span id="cb5-30"><a href="#cb5-30" aria-hidden="true" tabindex="-1"></a>peak_province <span class="ot">&lt;-</span> study<span class="sc">$</span>province[<span class="fu">st_intersects</span>(peak_sf, study)[[<span class="dv">1</span>]]]</span>
<span id="cb5-31"><a href="#cb5-31" aria-hidden="true" tabindex="-1"></a>peak_ll <span class="ot">&lt;-</span> <span class="fu">st_coordinates</span>(<span class="fu">st_transform</span>(peak_sf, <span class="dv">4326</span>))[<span class="dv">1</span>, ]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
</section>
</section>
<section id="task-3-second-order-analysis" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="task-3-second-order-analysis"><span class="header-section-number">5</span> Task 3 — Second-order analysis</h2>
<section id="what-is-the-comparison" class="level3" data-number="5.1">
<h3 data-number="5.1" class="anchored" data-anchor-id="what-is-the-comparison"><span class="header-section-number">5.1</span> What is the comparison?</h3>
<p>The question is whether the observed pattern departs from independent, spatially uniform placement inside the same window. Ripley’s K summarises neighbouring events within distance r; the transformation L(r) = √(K(r)/π) makes the Poisson reference L(r) − r = 0. Positive values indicate excess nearby pairs relative to that reference, rather than proof of a causal relationship between crashes.</p>
<p>Translation correction adjusts pair contributions for the overlap between the observation window and a shifted copy of it. This addresses boundary truncation under the method’s assumptions. It does not correct selective reporting or replace a road-network exposure model.</p>
<p>The test keeps the observed point count fixed. Each of 199 simulations places 530 independent uniform points in the same polygon. For each pattern, including the observed one, the test statistic is the maximum absolute deviation |L(r) − r| across the prespecified 0.25–10 km grid. The Monte Carlo p-value is (1 + number of simulated statistics at least as large as observed) / 200.</p>
<p>The plotted band uses the 95th percentile of simulated maximum deviations. It is a simultaneous, constant-width comparison over the selected grid, not a pointwise envelope or a confidence interval for the true L function. General envelope distinctions are discussed in the <a href="https://rdrr.io/cran/spatstat.explore/man/envelope.html">spatstat envelope documentation</a>.</p>
<div id="fig-csr" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-csr-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figures/csr-envelope.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-csr-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5: Translation-corrected L-function and global Monte Carlo comparison.
</figcaption>
</figure>
</div>
<div id="interpretation-csr">
<p>The observed curve exceeds the uniform-reference envelope. Its maximum absolute deviation is 3.834 km, compared with a simulated threshold of 0.275 km; the global Monte Carlo p-value is 0.005. Uniform independent placement is therefore not a plausible description of this recorded pattern. However, roads, travel activity, settlement, and recording coverage are spatially uneven. Rejection of uniformity does not show that separate crashes interact, or that the mapped concentrations imply greater individual risk.</p>
</div>
<div class="cell">
<details class="code-fold">
<summary>Show R code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Conditional CSR: retain n, independently sample uniform locations in the same polygon.</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>r <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">10000</span>, <span class="at">by =</span> <span class="dv">50</span>)</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>test_range <span class="ot">&lt;-</span> r <span class="sc">&gt;=</span> <span class="dv">250</span> <span class="sc">&amp;</span> r <span class="sc">&lt;=</span> <span class="dv">10000</span></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>l_curve <span class="ot">&lt;-</span> <span class="cf">function</span>(pattern) <span class="fu">Lest</span>(pattern, <span class="at">r =</span> r, <span class="at">correction =</span> <span class="st">"translate"</span>)<span class="sc">$</span>trans <span class="sc">-</span> r</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>observed_l <span class="ot">&lt;-</span> <span class="fu">l_curve</span>(X)</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>nsim <span class="ot">&lt;-</span> <span class="dv">199</span>L</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">20260910</span>)</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>simulated_l <span class="ot">&lt;-</span> <span class="fu">replicate</span>(nsim, <span class="fu">l_curve</span>(<span class="fu">runifpoint</span>(<span class="fu">npoints</span>(X), <span class="at">win =</span> W)))</span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>observed_stat <span class="ot">&lt;-</span> <span class="fu">max</span>(<span class="fu">abs</span>(observed_l[test_range]))</span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a>simulated_stats <span class="ot">&lt;-</span> <span class="fu">apply</span>(<span class="fu">abs</span>(simulated_l[test_range, , <span class="at">drop =</span> <span class="cn">FALSE</span>]), <span class="dv">2</span>, max)</span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a>p_global <span class="ot">&lt;-</span> (<span class="dv">1</span> <span class="sc">+</span> <span class="fu">sum</span>(simulated_stats <span class="sc">&gt;=</span> observed_stat)) <span class="sc">/</span> (nsim <span class="sc">+</span> <span class="dv">1</span>)</span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a>critical <span class="ot">&lt;-</span> <span class="fu">unname</span>(<span class="fu">quantile</span>(simulated_stats, <span class="fl">0.95</span>, <span class="at">type =</span> <span class="dv">1</span>))</span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a>csr_df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">distance_km =</span> r[test_range] <span class="sc">/</span> <span class="dv">1000</span>,</span>
<span id="cb6-14"><a href="#cb6-14" aria-hidden="true" tabindex="-1"></a>                     <span class="at">observed =</span> observed_l[test_range] <span class="sc">/</span> <span class="dv">1000</span>,</span>
<span id="cb6-15"><a href="#cb6-15" aria-hidden="true" tabindex="-1"></a>                     <span class="at">lower =</span> <span class="sc">-</span>critical <span class="sc">/</span> <span class="dv">1000</span>, <span class="at">upper =</span> critical <span class="sc">/</span> <span class="dv">1000</span>)</span>
<span id="cb6-16"><a href="#cb6-16" aria-hidden="true" tabindex="-1"></a>csr_plot <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(csr_df, <span class="fu">aes</span>(distance_km, observed)) <span class="sc">+</span></span>
<span id="cb6-17"><a href="#cb6-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_ribbon</span>(<span class="fu">aes</span>(<span class="at">ymin =</span> lower, <span class="at">ymax =</span> upper), <span class="at">fill =</span> <span class="st">"#dce8ed"</span>) <span class="sc">+</span></span>
<span id="cb6-18"><a href="#cb6-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="dv">0</span>, <span class="at">linetype =</span> <span class="dv">2</span>, <span class="at">colour =</span> <span class="st">"#788a98"</span>) <span class="sc">+</span></span>
<span id="cb6-19"><a href="#cb6-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">colour =</span> <span class="st">"#b34a31"</span>, <span class="at">linewidth =</span> <span class="fl">1.1</span>) <span class="sc">+</span></span>
<span id="cb6-20"><a href="#cb6-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Located fatalities depart from a spatially uniform reference"</span>,</span>
<span id="cb6-21"><a href="#cb6-21" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="fu">sprintf</span>(<span class="st">"Conditional CSR · 199 simulations · global MAD p = %.3f"</span>, p_global),</span>
<span id="cb6-22"><a href="#cb6-22" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Distance r (km)"</span>, <span class="at">y =</span> <span class="st">"L(r) − r (km)"</span>,</span>
<span id="cb6-23"><a href="#cb6-23" aria-hidden="true" tabindex="-1"></a>       <span class="at">caption =</span> <span class="st">"Translation edge correction. Band: global 95% Monte Carlo threshold for max |L(r)−r| over 0.25–10 km.</span><span class="sc">\n</span><span class="st">A rejection of uniformity does not isolate event interaction from spatially varying intensity."</span>)</span>
<span id="cb6-24"><a href="#cb6-24" aria-hidden="true" tabindex="-1"></a><span class="fu">save_plot</span>(csr_plot, <span class="st">"csr-envelope.png"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
</section>
<section id="allowing-intensity-to-vary" class="level3" data-number="5.2">
<h3 data-number="5.2" class="anchored" data-anchor-id="allowing-intensity-to-vary"><span class="header-section-number">5.2</span> Allowing intensity to vary</h3>
<p>An inhomogeneous K function reweights pairs using estimated local intensities. Here, intensity is estimated leave-one-out so a point does not contribute to its own estimate. The <a href="https://rdrr.io/cran/spatstat.explore/man/Kinhom.html">Kinhom documentation</a> explains this approach and the Poisson reference. Translation correction and renormalisation with power 2 are used.</p>
<p>These curves are <strong>descriptive diagnostics</strong>, not a calibrated second hypothesis test. A suitable formal test would also account for estimating the intensity surface. The diagnostic still assumes that its intensity model and second-order structure are meaningful for the observation process.</p>
<div id="fig-inhom" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-inhom-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figures/inhomogeneous-sensitivity.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-inhom-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6: Inhomogeneous L-function under bandwidth and coincidence sensitivity checks.
</figcaption>
</figure>
</div>
<div id="interpretation-inhom">
<p>The result changes materially with bandwidth. At 1 km, L-inhomogeneous(r) − r is −0.312 km using 3 km smoothing but +0.820 km using 6 km. The 3 km curve also jumps sharply near the upper end of the distance range. Collapsing repeated locations changes the curve but does not resolve bandwidth sensitivity. Without a calibrated envelope, negative values are not evidence of significant regularity. These diagnostics do not support a stable conclusion about residual interaction.</p>
</div>
<p>An intensity-weight check helps explain the instability. At 3 km bandwidth, one point contributes <strong>30.0% of the sum of inverse-intensity weights</strong>; at 6 km, the largest share is <strong>2.94%</strong>. This is not the share of the K statistic itself, but it shows how a low estimated intensity can give one location substantial influence. The sharp change should not be interpreted as a physical interaction threshold.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 15%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 34%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">Bandwidth (km)</th>
<th style="text-align: right;">Minimum intensity / km²</th>
<th style="text-align: right;">Maximum intensity / km²</th>
<th style="text-align: right;">Largest inverse-weight share (%)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">3</td>
<td style="text-align: right;">0.000207</td>
<td style="text-align: right;">0.318</td>
<td style="text-align: right;">29.97</td>
</tr>
<tr class="even">
<td style="text-align: right;">6</td>
<td style="text-align: right;">0.004577</td>
<td style="text-align: right;">0.251</td>
<td style="text-align: right;">2.94</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
</section>
<section id="task-4-integration-and-sensitivity" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="task-4-integration-and-sensitivity"><span class="header-section-number">6</span> Task 4 — Integration and sensitivity</h2>
<p>The first-order maps show uneven observed intensity, especially within Bangkok. The ordinary L-function agrees that a uniform spatial reference is inadequate. These findings complement each other, but they do not provide two independent proofs of crash interaction: spatially varying intensity can produce the ordinary L-function result.</p>
<p>The inhomogeneous diagnostic changes the interpretation. Results depend on the intensity bandwidth and, at 3 km, on influential low-intensity locations. It would be misleading to select one curve and label the pattern “clustered” or “regular” without acknowledging this instability.</p>
<p>Repeated coordinates are another concern. Removing coincident locations reduces the pattern from 530 records to 503 locations. At 10 km, ordinary L(r) − r changes only from 3.834 to 3.806 km; at 1 km it falls from 0.893 to 0.726 km. Coincident records matter more at short distances, but they do not explain the broad ordinary-L departure. This sensitivity changes the event unit and is not a reconstruction of distinct accidents. No separate p-value is claimed for that comparison.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 19%">
<col style="width: 36%">
<col style="width: 43%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">Distance (km)</th>
<th style="text-align: right;">All records: L(r) − r (km)</th>
<th style="text-align: right;">Unique locations: L(r) − r (km)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.893</td>
<td style="text-align: right;">0.726</td>
</tr>
<tr class="even">
<td style="text-align: right;">3</td>
<td style="text-align: right;">1.274</td>
<td style="text-align: right;">1.250</td>
</tr>
<tr class="odd">
<td style="text-align: right;">5</td>
<td style="text-align: right;">1.936</td>
<td style="text-align: right;">1.931</td>
</tr>
<tr class="even">
<td style="text-align: right;">10</td>
<td style="text-align: right;">3.834</td>
<td style="text-align: right;">3.806</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="cell">
<details class="code-fold">
<summary>Show R code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Descriptive inhomogeneous L curves, not a calibrated hypothesis test.</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Intensity is re-estimated leave-one-out at each point and bandwidth.</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>inhom_curve <span class="ot">&lt;-</span> <span class="cf">function</span>(pattern, h) {</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>  kval <span class="ot">&lt;-</span> <span class="fu">Kinhom</span>(pattern, <span class="at">sigma =</span> h, <span class="at">r =</span> r, <span class="at">correction =</span> <span class="st">"translate"</span>,</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>                <span class="at">leaveoneout =</span> <span class="cn">TRUE</span>, <span class="at">renormalise =</span> <span class="cn">TRUE</span>, <span class="at">normpower =</span> <span class="dv">2</span>)</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">sqrt</span>(<span class="fu">pmax</span>(kval<span class="sc">$</span>trans, <span class="dv">0</span>) <span class="sc">/</span> pi) <span class="sc">-</span> r</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>inhom <span class="ot">&lt;-</span> <span class="fu">bind_rows</span>(<span class="fu">lapply</span>(<span class="fu">c</span>(<span class="dv">3000</span>, <span class="dv">6000</span>), <span class="cf">function</span>(h) {</span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">data.frame</span>(<span class="at">distance_km =</span> r[test_range] <span class="sc">/</span> <span class="dv">1000</span>,</span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a>             <span class="at">value =</span> <span class="fu">inhom_curve</span>(X, h)[test_range] <span class="sc">/</span> <span class="dv">1000</span>,</span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a>             <span class="at">curve =</span> <span class="fu">paste0</span>(<span class="st">"All records; bandwidth "</span>, h<span class="sc">/</span><span class="dv">1000</span>, <span class="st">" km"</span>))</span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a>}), <span class="fu">data.frame</span>(<span class="at">distance_km =</span> r[test_range] <span class="sc">/</span> <span class="dv">1000</span>,</span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a>               <span class="at">value =</span> <span class="fu">inhom_curve</span>(X_unique, <span class="dv">3000</span>)[test_range] <span class="sc">/</span> <span class="dv">1000</span>,</span>
<span id="cb7-14"><a href="#cb7-14" aria-hidden="true" tabindex="-1"></a>               <span class="at">curve =</span> <span class="st">"Unique locations; bandwidth 3 km"</span>))</span>
<span id="cb7-15"><a href="#cb7-15" aria-hidden="true" tabindex="-1"></a>inhom_plot <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(inhom, <span class="fu">aes</span>(distance_km, value, <span class="at">colour =</span> curve)) <span class="sc">+</span></span>
<span id="cb7-16"><a href="#cb7-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="dv">0</span>, <span class="at">linetype =</span> <span class="dv">2</span>, <span class="at">colour =</span> <span class="st">"#788a98"</span>) <span class="sc">+</span> <span class="fu">geom_line</span>(<span class="at">linewidth =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb7-17"><a href="#cb7-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_colour_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"#176f82"</span>, <span class="st">"#b34a31"</span>, <span class="st">"#6c5c8d"</span>), <span class="at">name =</span> <span class="cn">NULL</span>) <span class="sc">+</span></span>
<span id="cb7-18"><a href="#cb7-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Residual pattern depends on the intensity estimate"</span>,</span>
<span id="cb7-19"><a href="#cb7-19" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"Inhomogeneous L(r) − r · translation correction · leave-one-out intensity"</span>,</span>
<span id="cb7-20"><a href="#cb7-20" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Distance r (km)"</span>, <span class="at">y =</span> <span class="st">"Inhomogeneous L(r) − r (km)"</span>,</span>
<span id="cb7-21"><a href="#cb7-21" aria-hidden="true" tabindex="-1"></a>       <span class="at">caption =</span> <span class="st">"The dashed line is the Poisson theoretical reference. No significance envelope is fitted here.</span><span class="sc">\n</span><span class="st">Unique-location sensitivity removes coincident records; it does not identify unique crashes."</span>)</span>
<span id="cb7-22"><a href="#cb7-22" aria-hidden="true" tabindex="-1"></a><span class="fu">save_plot</span>(inhom_plot, <span class="st">"inhomogeneous-sensitivity.png"</span>)</span>
<span id="cb7-23"><a href="#cb7-23" aria-hidden="true" tabindex="-1"></a>unique_l <span class="ot">&lt;-</span> <span class="fu">l_curve</span>(X_unique)</span>
<span id="cb7-24"><a href="#cb7-24" aria-hidden="true" tabindex="-1"></a>intensity_diagnostics <span class="ot">&lt;-</span> <span class="fu">bind_rows</span>(<span class="fu">lapply</span>(<span class="fu">c</span>(<span class="dv">3000</span>, <span class="dv">6000</span>), <span class="cf">function</span>(h) {</span>
<span id="cb7-25"><a href="#cb7-25" aria-hidden="true" tabindex="-1"></a>  lambda <span class="ot">&lt;-</span> <span class="fu">density</span>(X, <span class="at">sigma =</span> h, <span class="at">edge =</span> <span class="cn">TRUE</span>, <span class="at">at =</span> <span class="st">"points"</span>, <span class="at">leaveoneout =</span> <span class="cn">TRUE</span>)</span>
<span id="cb7-26"><a href="#cb7-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stopifnot</span>(<span class="fu">all</span>(<span class="fu">is.finite</span>(lambda)), <span class="fu">all</span>(lambda <span class="sc">&gt;</span> <span class="dv">0</span>))</span>
<span id="cb7-27"><a href="#cb7-27" aria-hidden="true" tabindex="-1"></a>  <span class="fu">data.frame</span>(<span class="at">bandwidth_km =</span> h<span class="sc">/</span><span class="dv">1000</span>, <span class="at">min_intensity_km2 =</span> <span class="fu">min</span>(lambda)<span class="sc">*</span><span class="fl">1e6</span>,</span>
<span id="cb7-28"><a href="#cb7-28" aria-hidden="true" tabindex="-1"></a>             <span class="at">max_intensity_km2 =</span> <span class="fu">max</span>(lambda)<span class="sc">*</span><span class="fl">1e6</span>,</span>
<span id="cb7-29"><a href="#cb7-29" aria-hidden="true" tabindex="-1"></a>             <span class="at">largest_inverse_intensity_share_pct =</span> <span class="dv">100</span> <span class="sc">*</span> <span class="fu">max</span>(<span class="dv">1</span><span class="sc">/</span>lambda) <span class="sc">/</span> <span class="fu">sum</span>(<span class="dv">1</span><span class="sc">/</span>lambda))</span>
<span id="cb7-30"><a href="#cb7-30" aria-hidden="true" tabindex="-1"></a>}))</span>
<span id="cb7-31"><a href="#cb7-31" aria-hidden="true" tabindex="-1"></a>at_distances <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1000</span>, <span class="dv">3000</span>, <span class="dv">5000</span>, <span class="dv">10000</span>)</span>
<span id="cb7-32"><a href="#cb7-32" aria-hidden="true" tabindex="-1"></a>l_summary <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">distance_km =</span> at_distances <span class="sc">/</span> <span class="dv">1000</span>,</span>
<span id="cb7-33"><a href="#cb7-33" aria-hidden="true" tabindex="-1"></a>                        <span class="at">all_records_L_minus_r_km =</span> observed_l[<span class="fu">match</span>(at_distances, r)] <span class="sc">/</span> <span class="dv">1000</span>,</span>
<span id="cb7-34"><a href="#cb7-34" aria-hidden="true" tabindex="-1"></a>                        <span class="at">unique_locations_L_minus_r_km =</span> unique_l[<span class="fu">match</span>(at_distances, r)] <span class="sc">/</span> <span class="dv">1000</span>)</span>
<span id="cb7-35"><a href="#cb7-35" aria-hidden="true" tabindex="-1"></a>inhom_summary <span class="ot">&lt;-</span> inhom <span class="sc">%&gt;%</span> <span class="fu">filter</span>(distance_km <span class="sc">%in%</span> (at_distances<span class="sc">/</span><span class="dv">1000</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p>Together, the checks favour a restrained conclusion: <strong>there is a clear concentration of located fatality records, but the current data and intensity model do not establish robust interaction between separate crashes</strong>. More advanced methods would not automatically resolve the missing-location and event-definition problems.</p>
</section>
<section id="task-5-geovisualisation-and-communication" class="level2" data-number="7">
<h2 data-number="7" class="anchored" data-anchor-id="task-5-geovisualisation-and-communication"><span class="header-section-number">7</span> Task 5 — Geovisualisation and communication</h2>
<p>Each major figure has a short interpretation immediately beneath it. The study map provides geographic context before the density maps; the KDE panels share one legend so colours remain comparable. Count charts retain zero baselines. The statistical plots label distances in kilometres and distinguish the theoretical reference from simulated evidence. The inhomogeneous diagnostic deliberately has no significance shading.</p>
<p>Maps use a colour gradient for magnitude rather than labelling arbitrary bands as “safe” or “dangerous”. The displayed figures and their interpretations support the same event definition and observation period.</p>
</section>
<section id="task-6-public-safety-planning-and-management" class="level2" data-number="8">
<h2 data-number="8" class="anchored" data-anchor-id="task-6-public-safety-planning-and-management"><span class="header-section-number">8</span> Task 6 — Public-safety planning and management</h2>
<div id="planning-discussion">
<p>The main practical use of this analysis is to identify broad areas for closer investigation. Bangkok contains 232 of the 530 located records, and its concentration remains visible under different KDE bandwidths. Agencies could use this as a starting point for reviewing existing fatal-crash case files and checking whether known problem locations are represented. The map alone is insufficient for choosing individual roads for engineering work.</p>
<p>Improving location recording should be a priority alongside hotspot review. Nearly three quarters of distinct records in the national extract have no coordinates, and availability differs across province-of-death groups. A consistent process for recording crash coordinates, location accuracy, and event identifiers would make future spatial comparisons more credible. Linking multiple fatalities to a shared crash identifier would also help distinguish the number of deaths from the number of crashes.</p>
<p>Decisions about enforcement, road redesign, or emergency response need information that is missing here. Traffic volumes, road type, speed, intersection layout, pedestrian activity, and emergency access could help assess whether a concentration reflects greater exposure, preventable hazards, or reporting differences. These are proposed follow-up inputs, not causes established by this study.</p>
<p>The results should not be used to reduce resources in areas with few mapped records. A sparse map may reflect incomplete geocoding. Similarly, the January count is not sufficient evidence for a seasonal deployment strategy because the available dates concern confirmed deaths, the extract stops in September, and monthly observation completeness is unknown.</p>
<p>A reasonable next step is a joint data-quality and site-review exercise: verify the locations and event identities in the broad concentration areas, compare them with independent operational records, and then assess particular interventions using exposure and road-condition evidence.</p>
</div>
</section>
<section id="limitations-and-conclusion" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="limitations-and-conclusion">Limitations and conclusion</h2>
<p>The dominant limitation is selective location availability. The analysis concerns 530 geocoded records, not all road fatalities in Greater Bangkok. The source’s national completeness and integration procedures have not been independently verified. The date field records confirmed deaths and covers nine months; it cannot support full-year or precise accident-time conclusions.</p>
<p>The assumed WGS 84 datum, unknown coordinate accuracy, older administrative boundaries, and planar treatment of road events add uncertainty. Multiple records can refer to one crash, while exact-row deduplication relies on released attributes. Edge correction does not solve these problems.</p>
<p>The evidence answers the research question in two parts. Located records are concentrated, with a prominent broad concentration within Bangkok. However, the sensitivity of the intensity-adjusted curves means that residual interaction is unresolved. This is useful as an exploratory account of recorded locations and a guide to further data checking, rather than a road-risk ranking.</p>
</section>
<section id="reproducibility" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="reproducibility">Reproducibility</h2>
<p>The complete workflow is in <a href="https://github.com/yufanyou2025/ISS626-VAA/blob/master/Take-home_Ex/Take-home_Ex01/analysis.R">analysis.R</a>. Expand the code sections above to see the exact preparation, plotting, and simulation code. The report executes that script once before displaying its results; the expanded blocks display the same code without executing it twice.</p>
<p>Original input hashes are checked before analysis. Raw files remain outside Git because the Kaggle licence label does not establish clear redistribution permission. The repository includes download instructions, metadata, checksums, aggregated outputs, and package versions. The boundary source is pinned to a specific revision. No individual record is included in the downloadable result tables.</p>
<p>From the repository root, obtain the inputs described in <code>data/README.md</code>, then run:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb8"><pre class="sourceCode powershell code-with-copy"><code class="sourceCode powershell"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>Rscript Take-home_Ex<span class="op">/</span>Take-home_Ex01<span class="op">/</span>analysis<span class="op">.</span><span class="fu">R</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>quarto render Take-home_Ex<span class="op">/</span>Take-home_Ex01<span class="op">/</span>technical-report<span class="op">.</span><span class="fu">qmd</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>quarto render Take-home_Ex<span class="op">/</span>Take-home_Ex01<span class="op">/</span>executive-summary<span class="op">.</span><span class="fu">qmd</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>The R script writes the figures and result tables. Rendering the report reruns the full analysis with the fixed simulation seed. The slides use the same saved figures and summary values. On Windows, <code>render.ps1</code> sets a supported UTF-8 locale for the render process and restores the previous environment afterwards.</p>
<div class="cell">
<details class="code-fold">
<summary>Show R code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Presentation variants use the same plotted evidence with larger labels.</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>slide_plots <span class="ot">&lt;-</span> <span class="fu">list</span>(<span class="at">coverage =</span> coverage_plot, <span class="at">study =</span> study_plot, <span class="at">monthly =</span> monthly_plot,</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>                    <span class="at">kde =</span> kde_plot, <span class="at">csr =</span> csr_plot, <span class="at">inhom =</span> inhom_plot)</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (name <span class="cf">in</span> <span class="fu">names</span>(slide_plots)) {</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>  plot <span class="ot">&lt;-</span> slide_plots[[name]] <span class="sc">+</span> <span class="fu">labs</span>(<span class="at">title =</span> <span class="cn">NULL</span>, <span class="at">subtitle =</span> <span class="cn">NULL</span>, <span class="at">caption =</span> <span class="cn">NULL</span>) <span class="sc">+</span></span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme</span>(<span class="at">text =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">17</span>), <span class="at">legend.text =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">14</span>),</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>          <span class="at">legend.title =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">14</span>))</span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (name <span class="sc">==</span> <span class="st">"inhom"</span>) plot <span class="ot">&lt;-</span> plot <span class="sc">+</span> <span class="fu">guides</span>(<span class="at">colour =</span> <span class="fu">guide_legend</span>(<span class="at">nrow =</span> <span class="dv">2</span>))</span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>  <span class="cf">for</span> (i <span class="cf">in</span> <span class="fu">seq_along</span>(plot<span class="sc">$</span>layers)) {</span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> (<span class="fu">inherits</span>(plot<span class="sc">$</span>layers[[i]]<span class="sc">$</span>geom, <span class="st">"GeomText"</span>) <span class="sc">||</span> <span class="fu">inherits</span>(plot<span class="sc">$</span>layers[[i]]<span class="sc">$</span>geom, <span class="st">"GeomLabel"</span>)) {</span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a>      plot<span class="sc">$</span>layers[[i]]<span class="sc">$</span>aes_params<span class="sc">$</span>size <span class="ot">&lt;-</span> <span class="fl">4.5</span></span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a>    }</span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb9-14"><a href="#cb9-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">save_plot</span>(plot, <span class="fu">paste0</span>(<span class="st">"slide-"</span>, name, <span class="st">".png"</span>), <span class="at">width =</span> <span class="dv">12</span>, <span class="at">height =</span> <span class="fl">5.5</span>)</span>
<span id="cb9-15"><a href="#cb9-15" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb9-16"><a href="#cb9-16" aria-hidden="true" tabindex="-1"></a>summary <span class="ot">&lt;-</span> <span class="fu">list</span>(</span>
<span id="cb9-17"><a href="#cb9-17" aria-hidden="true" tabindex="-1"></a>  <span class="at">raw_records =</span> <span class="fu">nrow</span>(raw), <span class="at">exact_duplicate_rows =</span> exact_duplicates,</span>
<span id="cb9-18"><a href="#cb9-18" aria-hidden="true" tabindex="-1"></a>  <span class="at">deduplicated_records =</span> <span class="fu">nrow</span>(dat), <span class="at">located_national =</span> <span class="fu">nrow</span>(located),</span>
<span id="cb9-19"><a href="#cb9-19" aria-hidden="true" tabindex="-1"></a>  <span class="at">missing_coordinates =</span> <span class="fu">sum</span>(<span class="sc">!</span>period<span class="sc">$</span>has_coordinates),</span>
<span id="cb9-20"><a href="#cb9-20" aria-hidden="true" tabindex="-1"></a>  <span class="at">missing_coordinates_pct =</span> <span class="dv">100</span> <span class="sc">*</span> <span class="fu">mean</span>(<span class="sc">!</span>period<span class="sc">$</span>has_coordinates),</span>
<span id="cb9-21"><a href="#cb9-21" aria-hidden="true" tabindex="-1"></a>  <span class="at">study_records =</span> <span class="fu">npoints</span>(X), <span class="at">unique_locations =</span> <span class="fu">npoints</span>(X_unique),</span>
<span id="cb9-22"><a href="#cb9-22" aria-hidden="true" tabindex="-1"></a>  <span class="at">excess_coincident_records =</span> <span class="fu">npoints</span>(X) <span class="sc">-</span> <span class="fu">npoints</span>(X_unique),</span>
<span id="cb9-23"><a href="#cb9-23" aria-hidden="true" tabindex="-1"></a>  <span class="at">distinct_location_dates =</span> <span class="fu">nrow</span>(<span class="fu">distinct</span>(<span class="fu">st_drop_geometry</span>(pts), longitude, latitude, death_date)),</span>
<span id="cb9-24"><a href="#cb9-24" aria-hidden="true" tabindex="-1"></a>  <span class="at">observation_start =</span> <span class="fu">as.character</span>(<span class="fu">min</span>(period<span class="sc">$</span>death_date)), <span class="at">observation_end =</span> <span class="fu">as.character</span>(<span class="fu">max</span>(period<span class="sc">$</span>death_date)),</span>
<span id="cb9-25"><a href="#cb9-25" aria-hidden="true" tabindex="-1"></a>  <span class="at">study_start =</span> <span class="fu">as.character</span>(<span class="fu">min</span>(pts<span class="sc">$</span>death_date)), <span class="at">study_end =</span> <span class="fu">as.character</span>(<span class="fu">max</span>(pts<span class="sc">$</span>death_date)),</span>
<span id="cb9-26"><a href="#cb9-26" aria-hidden="true" tabindex="-1"></a>  <span class="at">area_km2 =</span> area_km2, <span class="at">average_intensity_per_km2 =</span> <span class="fu">npoints</span>(X) <span class="sc">/</span> area_km2,</span>
<span id="cb9-27"><a href="#cb9-27" aria-hidden="true" tabindex="-1"></a>  <span class="at">invalid_selected_boundaries =</span> invalid_boundaries, <span class="at">ambiguous_province_boundaries =</span> ambiguous_boundaries,</span>
<span id="cb9-28"><a href="#cb9-28" aria-hidden="true" tabindex="-1"></a>  <span class="at">global_csr_p =</span> p_global, <span class="at">global_csr_stat_km =</span> observed_stat<span class="sc">/</span><span class="dv">1000</span>,</span>
<span id="cb9-29"><a href="#cb9-29" aria-hidden="true" tabindex="-1"></a>  <span class="at">global_csr_critical_km =</span> critical<span class="sc">/</span><span class="dv">1000</span>, <span class="at">simulations =</span> nsim, <span class="at">seed =</span> <span class="dv">20260910</span>,</span>
<span id="cb9-30"><a href="#cb9-30" aria-hidden="true" tabindex="-1"></a>  <span class="at">peak_3km_intensity =</span> peak<span class="sc">$</span>intensity, <span class="at">peak_province =</span> peak_province,</span>
<span id="cb9-31"><a href="#cb9-31" aria-hidden="true" tabindex="-1"></a>  <span class="at">peak_longitude =</span> <span class="fu">unname</span>(peak_ll[<span class="dv">1</span>]), <span class="at">peak_latitude =</span> <span class="fu">unname</span>(peak_ll[<span class="dv">2</span>]),</span>
<span id="cb9-32"><a href="#cb9-32" aria-hidden="true" tabindex="-1"></a>  <span class="at">kde_peak_intensities =</span> <span class="fu">vapply</span>(kde_frames, <span class="cf">function</span>(z) <span class="fu">max</span>(z<span class="sc">$</span>intensity), <span class="fu">numeric</span>(<span class="dv">1</span>)))</span>
<span id="cb9-33"><a href="#cb9-33" aria-hidden="true" tabindex="-1"></a>jsonlite<span class="sc">::</span><span class="fu">write_json</span>(summary, <span class="fu">file.path</span>(out_dir, <span class="st">"summary.json"</span>), <span class="at">pretty =</span> <span class="cn">TRUE</span>, <span class="at">auto_unbox =</span> <span class="cn">TRUE</span>, <span class="at">digits =</span> <span class="dv">10</span>)</span>
<span id="cb9-34"><a href="#cb9-34" aria-hidden="true" tabindex="-1"></a>tables <span class="ot">&lt;-</span> <span class="fu">list</span>(<span class="at">audit =</span> audit, <span class="at">coverage =</span> coverage, <span class="at">province_counts =</span> province_table,</span>
<span id="cb9-35"><a href="#cb9-35" aria-hidden="true" tabindex="-1"></a>               <span class="at">monthly =</span> monthly, <span class="at">l_summary =</span> l_summary, <span class="at">inhom_summary =</span> inhom_summary,</span>
<span id="cb9-36"><a href="#cb9-36" aria-hidden="true" tabindex="-1"></a>               <span class="at">csr_curve =</span> csr_df, <span class="at">inhom_curves =</span> inhom, <span class="at">intensity_diagnostics =</span> intensity_diagnostics)</span>
<span id="cb9-37"><a href="#cb9-37" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (name <span class="cf">in</span> <span class="fu">names</span>(tables)) readr<span class="sc">::</span><span class="fu">write_csv</span>(tables[[name]], <span class="fu">file.path</span>(out_dir, <span class="fu">paste0</span>(name, <span class="st">".csv"</span>)))</span>
<span id="cb9-38"><a href="#cb9-38" aria-hidden="true" tabindex="-1"></a><span class="fu">writeLines</span>(<span class="fu">capture.output</span>(<span class="fu">sessionInfo</span>()), <span class="fu">file.path</span>(out_dir, <span class="st">"session-info.txt"</span>))</span>
<span id="cb9-39"><a href="#cb9-39" aria-hidden="true" tabindex="-1"></a>versions <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">package =</span> required, <span class="at">version =</span> <span class="fu">vapply</span>(required, <span class="cf">function</span>(p) <span class="fu">as.character</span>(<span class="fu">packageVersion</span>(p)), <span class="fu">character</span>(<span class="dv">1</span>)))</span>
<span id="cb9-40"><a href="#cb9-40" aria-hidden="true" tabindex="-1"></a>readr<span class="sc">::</span><span class="fu">write_csv</span>(versions, <span class="fu">file.path</span>(out_dir, <span class="st">"package-versions.csv"</span>))</span>
<span id="cb9-41"><a href="#cb9-41" aria-hidden="true" tabindex="-1"></a><span class="fu">saveRDS</span>(<span class="fu">list</span>(<span class="at">summary =</span> summary, <span class="at">tables =</span> tables), <span class="fu">file.path</span>(out_dir, <span class="st">"report-results.rds"</span>))</span>
<span id="cb9-42"><a href="#cb9-42" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(jsonlite<span class="sc">::</span><span class="fu">toJSON</span>(summary, <span class="at">pretty =</span> <span class="cn">TRUE</span>, <span class="at">auto_unbox =</span> <span class="cn">TRUE</span>, <span class="at">digits =</span> <span class="dv">6</span>), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Package</th>
<th style="text-align: left;">Version</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">sf</td>
<td style="text-align: left;">1.1.2</td>
</tr>
<tr class="even">
<td style="text-align: left;">dplyr</td>
<td style="text-align: left;">1.2.1</td>
</tr>
<tr class="odd">
<td style="text-align: left;">readr</td>
<td style="text-align: left;">2.2.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">ggplot2</td>
<td style="text-align: left;">4.0.3</td>
</tr>
<tr class="odd">
<td style="text-align: left;">spatstat.geom</td>
<td style="text-align: left;">3.8.2</td>
</tr>
<tr class="even">
<td style="text-align: left;">spatstat.explore</td>
<td style="text-align: left;">3.8.2</td>
</tr>
<tr class="odd">
<td style="text-align: left;">spatstat.random</td>
<td style="text-align: left;">3.5.1</td>
</tr>
<tr class="even">
<td style="text-align: left;">jsonlite</td>
<td style="text-align: left;">2.0.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">digest</td>
<td style="text-align: left;">0.6.39</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>R session information
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>R version 4.6.1 (2026-06-24 ucrt)
Platform: x86_64-w64-mingw32/x64
Running under: Windows 10 x64 (build 19045)

Matrix products: default
  LAPACK version 3.12.1

locale:
[1] LC_COLLATE=English_United States.utf8 
[2] LC_CTYPE=English_United States.utf8   
[3] LC_MONETARY=English_United States.utf8
[4] LC_NUMERIC=C                          
[5] LC_TIME=English_United States.utf8    

time zone: Asia/Singapore
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] spatstat.explore_3.8-2 nlme_3.1-169           spatstat.random_3.5-1 
[4] spatstat.geom_3.8-2    spatstat.univar_3.2-0  spatstat.data_3.1-9   
[7] ggplot2_4.0.3          dplyr_1.2.1            sf_1.1-2              

loaded via a namespace (and not attached):
 [1] gtable_0.3.6          xfun_0.60             htmlwidgets_1.6.4    
 [4] spatstat.sparse_3.2-0 lattice_0.22-9        tzdb_0.5.0           
 [7] vctrs_0.7.3           tools_4.6.1           spatstat.utils_3.2-4 
[10] generics_0.1.4        goftest_1.2-3         parallel_4.6.1       
[13] tibble_3.3.1          proxy_0.4-29          pkgconfig_2.0.3      
[16] Matrix_1.7-5          KernSmooth_2.23-26    RColorBrewer_1.1-3   
[19] S7_0.2.2              lifecycle_1.0.5       compiler_4.6.1       
[22] farver_2.1.2          deldir_2.0-4          textshaping_1.0.5    
[25] htmltools_0.5.9       class_7.3-23          yaml_2.3.12          
[28] pillar_1.11.1         crayon_1.5.3          classInt_0.4-11      
[31] wk_0.9.5              abind_1.4-8           tidyselect_1.2.1     
[34] digest_0.6.39         labeling_0.4.3        polyclip_1.10-7      
[37] fastmap_1.2.0         grid_4.6.1            cli_3.6.6            
[40] magrittr_2.0.5        e1071_1.7-17          readr_2.2.0          
[43] withr_3.0.3           tensor_1.5.1          scales_1.4.0         
[46] bit64_4.8.4           rmarkdown_2.31        bit_4.6.0            
[49] otel_0.2.0            ragg_1.5.2            hms_1.1.4            
[52] evaluate_1.0.5        knitr_1.51            viridisLite_0.4.3    
[55] s2_1.1.11             rlang_1.3.0           Rcpp_1.1.2           
[58] glue_1.8.1            DBI_1.3.0             vroom_1.7.1          
[61] jsonlite_2.0.0        R6_2.6.1              systemfonts_1.3.2    
[64] units_1.0-1          </code></pre>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="references" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="references">References</h2>
<ol type="1">
<li>ISSS626 (2026). <a href="https://isss626-ay2026-27aug.netlify.app/take-home_ex01">Take-home Exercise 1: Geospatial Analytics for Public Safety</a>. Assignment requirements and course policy.</li>
<li>Kamchan, P. (2025). <a href="https://www.kaggle.com/datasets/pornsakkamchan/thailand-road-accident-fatalities-2024">Thailand Road Accident Fatalities 2024</a>, version 1. Accessed 10 September 2026.</li>
<li>geoBoundaries. <a href="https://www.geoboundaries.org/api/current/gbOpen/THA/ADM1/">Thailand ADM1 metadata</a> and <a href="https://github.com/wmgeolab/geoBoundaries/raw/9469f09/releaseData/gbOpen/THA/ADM1/geoBoundaries-THA-ADM1.geojson">pinned boundary data</a>. OpenStreetMap and Wambacher attribution; <a href="https://www.openstreetmap.org/copyright">ODbL information</a>.</li>
<li>National Statistical Office of Thailand. <a href="https://catalogapi.nso.go.th/api/doc/department/D10/SD10_04/SD10_04_265_1.pdf?preview=1">Statistical documentation: Bangkok and Vicinities</a>. Geographic grouping.</li>
<li>ISSS626. <a href="https://isss626-ay2026-27aug.netlify.app/lesson/Lesson02/Lesson02-SPPA.html">Lesson 2: Spatial Point Patterns Analysis</a>.</li>
<li>Pebesma, E. <a href="https://r-spatial.github.io/sf/articles/sf1.html">Simple Features for R</a>.</li>
<li>Baddeley, A., Rubak, E., and Turner, R. <a href="https://spatstat.org/">spatstat documentation and learning resources</a>.</li>
<li>spatstat.explore. <a href="https://rdrr.io/cran/spatstat.explore/man/Kinhom.html">Kinhom documentation</a> and <a href="https://rdrr.io/cran/spatstat.explore/man/envelope.html">simulation envelope documentation</a>. Package version 3.8.2 used locally.</li>
</ol>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>