<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="yufanyou2025">
<meta name="dcterms.date" content="2026-09-18">

<title>Hands-on Exercise 3: Spatio-temporal Point Patterns – ISS626-VAA</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-172ba59bd5e0b52282274ba0c0cc16fc.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@4/tex-chtml.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="/index.html">
    <span class="navbar-title">ISS626-VAA</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-take-home-exercise" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Take-home Exercise</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-take-home-exercise">    
        <li>
    <a class="dropdown-item" href="/Take-home_Ex/Take-home_Ex01/technical-report.html">
 <span class="dropdown-text">Exercise 1: Technical Report</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="/Take-home_Ex/Take-home_Ex01/executive-summary.html">
 <span class="dropdown-text">Exercise 1: Executive Summary</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://github.com/yufanyou2025/ISS626-VAA">
 <span class="dropdown-text">GitHub repository</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-hands-on-exercise" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Hands-on Exercise</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-hands-on-exercise">    
        <li>
    <a class="dropdown-item" href="/Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01a.html">
 <span class="dropdown-text">Hands-on Exercise 1A: Geospatial Data Science</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="/Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01b.html">
 <span class="dropdown-text">Hands-on Exercise 1B: Thematic Mapping</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="/Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02a.html">
 <span class="dropdown-text">Hands-on Exercise 2A: First-order Point Patterns</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="/Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02b.html">
 <span class="dropdown-text">Hands-on Exercise 2B: Second-order Point Patterns</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="/Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03.html">
 <span class="dropdown-text">Hands-on Exercise 3: Spatio-temporal Point Patterns</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="/Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04.html">
 <span class="dropdown-text">Hands-on Exercise 4: Spatial Weights and Applications</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-in-class-exercise" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">In-class Exercise</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-in-class-exercise">    
        <li>
    <a class="dropdown-item" href="/In-class_Ex/In-class_Ex04/In-class_Ex04.html">
 <span class="dropdown-text">In-class Exercise 4: Geographically Weighted Statistics</span></a>
  </li>  
    </ul>
  </li>
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="/index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="/about.html"> 
<span class="menu-text">About</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#overview-and-research-questions" id="toc-overview-and-research-questions" class="nav-link active" data-scroll-target="#overview-and-research-questions"><span class="header-section-number">1</span> Overview and research questions</a></li>
  <li><a href="#data-and-packages" id="toc-data-and-packages" class="nav-link" data-scroll-target="#data-and-packages"><span class="header-section-number">2</span> Data and packages</a></li>
  <li><a href="#preparing-the-study-area" id="toc-preparing-the-study-area" class="nav-link" data-scroll-target="#preparing-the-study-area"><span class="header-section-number">3</span> Preparing the study area</a>
  <ul class="collapse">
  <li><a href="#a-geographical-clarification" id="toc-a-geographical-clarification" class="nav-link" data-scroll-target="#a-geographical-clarification"><span class="header-section-number">3.1</span> A geographical clarification</a></li>
  </ul></li>
  <li><a href="#preparing-the-fire-observations" id="toc-preparing-the-fire-observations" class="nav-link" data-scroll-target="#preparing-the-fire-observations"><span class="header-section-number">4</span> Preparing the fire observations</a></li>
  <li><a href="#visualising-the-fire-points" id="toc-visualising-the-fire-points" class="nav-link" data-scroll-target="#visualising-the-fire-points"><span class="header-section-number">5</span> Visualising the fire points</a>
  <ul class="collapse">
  <li><a href="#overall-distribution" id="toc-overall-distribution" class="nav-link" data-scroll-target="#overall-distribution"><span class="header-section-number">5.1</span> Overall distribution</a></li>
  <li><a href="#monthly-distribution" id="toc-monthly-distribution" class="nav-link" data-scroll-target="#monthly-distribution"><span class="header-section-number">5.2</span> Monthly distribution</a></li>
  </ul></li>
  <li><a href="#computing-space-time-kde-by-month" id="toc-computing-space-time-kde-by-month" class="nav-link" data-scroll-target="#computing-space-time-kde-by-month"><span class="header-section-number">6</span> Computing space-time KDE by month</a></li>
  <li><a href="#computing-kde-by-day-of-year" id="toc-computing-kde-by-day-of-year" class="nav-link" data-scroll-target="#computing-kde-by-day-of-year"><span class="header-section-number">7</span> Computing KDE by day of year</a></li>
  <li><a href="#improved-day-based-kde-bandwidth-selection" id="toc-improved-day-based-kde-bandwidth-selection" class="nav-link" data-scroll-target="#improved-day-based-kde-bandwidth-selection"><span class="header-section-number">8</span> Improved day-based KDE: bandwidth selection</a>
  <ul class="collapse">
  <li><a href="#watching-the-pattern-change" id="toc-watching-the-pattern-change" class="nav-link" data-scroll-target="#watching-the-pattern-change"><span class="header-section-number">8.1</span> Watching the pattern change</a></li>
  </ul></li>
  <li><a href="#space-time-point-pattern-analysis-with-stpp" id="toc-space-time-point-pattern-analysis-with-stpp" class="nav-link" data-scroll-target="#space-time-point-pattern-analysis-with-stpp"><span class="header-section-number">9</span> Space-time point-pattern analysis with stpp</a>
  <ul class="collapse">
  <li><a href="#preparing-the-space-time-object" id="toc-preparing-the-space-time-object" class="nav-link" data-scroll-target="#preparing-the-space-time-object"><span class="header-section-number">9.1</span> Preparing the space-time object</a></li>
  <li><a href="#computing-the-space-time-k-function" id="toc-computing-the-space-time-k-function" class="nav-link" data-scroll-target="#computing-the-space-time-k-function"><span class="header-section-number">9.2</span> Computing the space-time K-function</a></li>
  <li><a href="#interpreting-the-surface" id="toc-interpreting-the-surface" class="nav-link" data-scroll-target="#interpreting-the-surface"><span class="header-section-number">9.3</span> Interpreting the surface</a></li>
  </ul></li>
  <li><a href="#what-i-learned" id="toc-what-i-learned" class="nav-link" data-scroll-target="#what-i-learned"><span class="header-section-number">10</span> What I learned</a></li>
  <li><a href="#reproducibility-and-references" id="toc-reproducibility-and-references" class="nav-link" data-scroll-target="#reproducibility-and-references"><span class="header-section-number">11</span> Reproducibility and references</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Hands-on Exercise 3: Spatio-temporal Point Patterns</h1>
<p class="subtitle lead">Following fire detections across Bangka through 2023</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>yufanyou2025 </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">September 18, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="overview-and-research-questions" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="overview-and-research-questions"><span class="header-section-number">1</span> Overview and research questions</h2>
<p>An annual map can show where fire detections are concentrated, but it hides whether those concentrations occurred together or months apart. Following <a href="https://r4gdsa.netlify.app/chap06">Workbook Chapter 6</a>, this exercise introduces time as a third dimension: location is represented by projected x and y coordinates, and acquisition date by month or day of year.</p>
<p>I examine three questions: when detections were most frequent, how the estimated spatial distribution changes through the year, and how observed space-time neighbourhoods compare with a homogeneous Poisson reference. The density maps are descriptive. The K-function is also interpreted cautiously: the chapter does not supply a simulation-based test of independence.</p>
</section>
<section id="data-and-packages" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="data-and-packages"><span class="header-section-number">2</span> Data and packages</h2>
<p>The fire observations come directly from <a href="https://firms.modaps.eosdis.nasa.gov/data/country/modis/2023/modis_2023_Indonesia.csv">NASA FIRMS’ 2023 MODIS Indonesia country file</a>, accessed on 18 September 2026. There are 52,156 country-wide records before clipping. These are satellite active-fire/thermal-anomaly detections, not a catalogue of unique forest-fire incidents or burned area. Repeated satellite observations can describe the same continuing fire, and detection depends on overpass timing, cloud cover and sensor resolution.</p>
<p>The boundary originates from the <a href="https://www.indonesia-geospasial.com/2023/05/download-shapefile-batas-administrasi.html">Indonesia Geospatial administrative-boundary dataset cited by the workbook</a>. I use its province extract from a <a href="https://github.com/Hungthq/ISSS626-GAA/tree/f7a95396d1088cb7356e3677a574ef20c28b62a0/data/geospatial">pinned public data mirror</a>, rather than downloading the much larger national archive. Only the boundary data are reused; this analysis and its interpretations are developed here. Boundary attributes identify a December 2022 compilation, with underlying delineation labels referring to 2019. The <a href="outputs/data-manifest.csv">download manifest</a> records the exact URLs, access date and checksums; it does not imply that the boundary was surveyed on the download date.</p>
<p>The R workflow uses <code>sf</code>, <code>spatstat.geom</code>, <code>sparr</code>, <code>stpp</code>, <code>tmap</code>, <code>dplyr</code>, <code>readr</code> and <code>lubridate</code>. <code>ggplot2</code> draws the count chart and <code>magick</code> exports the animation. <a href="prepare.R">prepare.R</a> downloads and checks the inputs, while <a href="analysis.R">analysis.R</a> computes the results. <a href="README.md">Reproduction instructions</a> and <a href="outputs/session-info.txt">session versions</a> are available for rerunning the work.</p>
</section>
<section id="preparing-the-study-area" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="preparing-the-study-area"><span class="header-section-number">3</span> Preparing the study area</h2>
<section id="a-geographical-clarification" class="level3" data-number="3.1">
<h3 data-number="3.1" class="anchored" data-anchor-id="a-geographical-clarification"><span class="header-section-number">3.1</span> A geographical clarification</h3>
<p>Although the chapter names the province of Kepulauan Bangka Belitung, its displayed extent and 297 subdistricts cover <strong>Bangka’s main island</strong>, not the separate island of Belitung. I reproduce that window explicitly: exclude the Belitung regencies, dissolve the remaining boundaries, and retain the largest connected polygon. The resulting area is approximately 11,534 km². Offshore polygons are not silently treated as part of the study.</p>
<p>The boundary is stripped of unused Z coordinates, repaired where necessary, and transformed to WGS 84 / UTM zone 48S (EPSG:32748). Metres are appropriate for the spatial distances used below. <code>as.owin()</code> turns the polygon into the observation window required by <code>spatstat</code>.</p>
<div class="cell">
<details class="code-fold">
<summary>Show R code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># The workbook's stated extent covers Bangka, not the eastern Belitung island.</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>boundary <span class="ot">&lt;-</span> boundary_raw <span class="sc">|&gt;</span> <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">grepl</span>(<span class="st">"Belitung"</span>,WADMKK,<span class="at">ignore.case=</span><span class="cn">TRUE</span>)) <span class="sc">|&gt;</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_zm</span>() <span class="sc">|&gt;</span> <span class="fu">st_transform</span>(<span class="dv">32748</span>) <span class="sc">|&gt;</span> <span class="fu">st_make_valid</span>()</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>components <span class="ot">&lt;-</span> <span class="fu">st_cast</span>(<span class="fu">st_union</span>(boundary),<span class="st">"POLYGON"</span>)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>study <span class="ot">&lt;-</span> components[<span class="fu">which.max</span>(<span class="fu">st_area</span>(components))]</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>boundary <span class="ot">&lt;-</span> boundary[<span class="fu">lengths</span>(<span class="fu">st_intersects</span>(<span class="fu">st_point_on_surface</span>(boundary),study))<span class="sc">&gt;</span><span class="dv">0</span>,]</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>window <span class="ot">&lt;-</span> <span class="fu">as.owin</span>(study)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>fire_2023 <span class="ot">&lt;-</span> fire_raw <span class="sc">|&gt;</span> <span class="fu">filter</span>(acq_date<span class="sc">&gt;=</span><span class="fu">as.Date</span>(<span class="st">"2023-01-01"</span>),acq_date<span class="sc">&lt;=</span><span class="fu">as.Date</span>(<span class="st">"2023-12-31"</span>))</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>fire_sf_all <span class="ot">&lt;-</span> <span class="fu">st_as_sf</span>(fire_2023,<span class="at">coords=</span><span class="fu">c</span>(<span class="st">"longitude"</span>,<span class="st">"latitude"</span>),<span class="at">crs=</span><span class="dv">4326</span>,<span class="at">remove=</span><span class="cn">FALSE</span>) <span class="sc">|&gt;</span> <span class="fu">st_transform</span>(<span class="dv">32748</span>)</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>keep <span class="ot">&lt;-</span> <span class="fu">lengths</span>(<span class="fu">st_intersects</span>(fire_sf_all,study))<span class="sc">&gt;</span><span class="dv">0</span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>fire_sf <span class="ot">&lt;-</span> fire_sf_all[keep,] <span class="sc">|&gt;</span> <span class="fu">mutate</span>(<span class="at">DayofYear=</span><span class="fu">yday</span>(acq_date),<span class="at">Month_num=</span><span class="fu">month</span>(acq_date))</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>coords <span class="ot">&lt;-</span> <span class="fu">st_coordinates</span>(fire_sf)</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>month_ppp <span class="ot">&lt;-</span> <span class="fu">ppp</span>(coords[,<span class="dv">1</span>],coords[,<span class="dv">2</span>],<span class="at">window=</span>window,<span class="at">marks=</span>fire_sf<span class="sc">$</span>Month_num,<span class="at">checkdup=</span><span class="cn">FALSE</span>)</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>day_ppp <span class="ot">&lt;-</span> <span class="fu">ppp</span>(coords[,<span class="dv">1</span>],coords[,<span class="dv">2</span>],<span class="at">window=</span>window,<span class="at">marks=</span>fire_sf<span class="sc">$</span>DayofYear,<span class="at">checkdup=</span><span class="cn">FALSE</span>)</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>monthly <span class="ot">&lt;-</span> <span class="fu">tibble</span>(<span class="at">month=</span><span class="dv">1</span><span class="sc">:</span><span class="dv">12</span>,<span class="at">month_name=</span>month.abb,<span class="at">count=</span><span class="fu">tabulate</span>(fire_sf<span class="sc">$</span>Month_num,<span class="at">nbins=</span><span class="dv">12</span>))</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>audit <span class="ot">&lt;-</span> <span class="fu">tibble</span>(<span class="at">measure=</span><span class="fu">c</span>(<span class="st">"Imported boundary features"</span>,<span class="st">"Bangka boundary features"</span>,<span class="st">"Indonesia detections"</span>,<span class="st">"Retained detections"</span>,<span class="st">"Outside study window"</span>,<span class="st">"Repeated XY coordinates"</span>,<span class="st">"Repeated XY-day records"</span>,<span class="st">"Window area km2"</span>),</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a> <span class="at">value=</span><span class="fu">c</span>(<span class="fu">nrow</span>(boundary_raw),<span class="fu">nrow</span>(boundary),<span class="fu">nrow</span>(fire_raw),<span class="fu">nrow</span>(fire_sf),<span class="fu">sum</span>(<span class="sc">!</span>keep),<span class="fu">sum</span>(<span class="fu">duplicated</span>(coords)),<span class="fu">sum</span>(<span class="fu">duplicated</span>(<span class="fu">cbind</span>(coords,fire_sf<span class="sc">$</span>DayofYear))),<span class="fu">area.owin</span>(window)<span class="sc">/</span><span class="fl">1e6</span>))</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a><span class="fu">write_csv</span>(audit,<span class="fu">file.path</span>(base,<span class="st">"outputs/audit.csv"</span>))</span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a><span class="fu">write_csv</span>(monthly,<span class="fu">file.path</span>(base,<span class="st">"outputs/monthly-counts.csv"</span>))</span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(<span class="fu">st_crs</span>(fire_sf)<span class="sc">$</span>epsg<span class="sc">==</span><span class="dv">32748</span>,<span class="fu">all</span>(<span class="fu">st_is_valid</span>(study)),<span class="fu">all</span>(<span class="fu">inside.owin</span>(coords[,<span class="dv">1</span>],coords[,<span class="dv">2</span>],window)))</span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(audit);<span class="fu">print</span>(monthly);<span class="fu">print</span>(<span class="fu">st_geometry_type</span>(study))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
</section>
</section>
<section id="preparing-the-fire-observations" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="preparing-the-fire-observations"><span class="header-section-number">4</span> Preparing the fire observations</h2>
<p>Longitude and latitude are first declared as WGS84 coordinates and then transformed—not merely relabelled—to EPSG:32748. I restrict acquisition dates to 2023 and retain detections intersecting the island polygon. <code>Month_num</code> gives the month and <code>DayofYear</code> counts days from 1 January.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Check</th>
<th style="text-align: right;">Result</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Imported boundary features</td>
<td style="text-align: right;">394.00</td>
</tr>
<tr class="even">
<td style="text-align: left;">Bangka boundary features</td>
<td style="text-align: right;">297.00</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Indonesia detections</td>
<td style="text-align: right;">52156.00</td>
</tr>
<tr class="even">
<td style="text-align: left;">Retained detections</td>
<td style="text-align: right;">741.00</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Outside study window</td>
<td style="text-align: right;">51415.00</td>
</tr>
<tr class="even">
<td style="text-align: left;">Repeated XY coordinates</td>
<td style="text-align: right;">0.00</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Repeated XY-day records</td>
<td style="text-align: right;">0.00</td>
</tr>
<tr class="even">
<td style="text-align: left;">Window area km2</td>
<td style="text-align: right;">11533.63</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The 741 retained detections match the workbook’s reported sample. There are no repeated XY coordinates or repeated XY-day combinations in this extract. The 51,415 exclusions are country-wide detections outside this island, not missing or invalid fire records. A detection remains an observation of a thermal anomaly; absence of exact duplicate coordinates does not establish that each observation represents a different fire.</p>
</section>
<section id="visualising-the-fire-points" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="visualising-the-fire-points"><span class="header-section-number">5</span> Visualising the fire points</h2>
<section id="overall-distribution" class="level3" data-number="5.1">
<h3 data-number="5.1" class="anchored" data-anchor-id="overall-distribution"><span class="header-section-number">5.1</span> Overall distribution</h3>
<div class="cell">
<details class="code-fold">
<summary>Show R code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_mode</span>(<span class="st">"plot"</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>overview <span class="ot">&lt;-</span> <span class="fu">tm_shape</span>(study)<span class="sc">+</span><span class="fu">tm_polygons</span>(<span class="at">fill=</span><span class="st">"#eee9dc"</span>)<span class="sc">+</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a> <span class="fu">tm_shape</span>(fire_sf)<span class="sc">+</span><span class="fu">tm_dots</span>(<span class="at">fill=</span><span class="st">"#9b462d"</span>,<span class="at">size=</span>.<span class="dv">035</span>)<span class="sc">+</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a> <span class="fu">tm_title</span>(<span class="st">"MODIS fire detections | Bangka, 2023"</span>)<span class="sc">+</span><span class="fu">tm_scalebar</span>(<span class="at">position=</span><span class="fu">c</span>(<span class="st">"left"</span>,<span class="st">"bottom"</span>))<span class="sc">+</span><span class="fu">tm_compass</span>(<span class="at">position=</span><span class="fu">c</span>(<span class="st">"right"</span>,<span class="st">"top"</span>))<span class="sc">+</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a> <span class="fu">tm_layout</span>(<span class="at">frame=</span><span class="cn">FALSE</span>)</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_save</span>(overview,<span class="fu">file.path</span>(base,<span class="st">"figures/fire-locations.png"</span>),<span class="at">width=</span><span class="dv">1800</span>,<span class="at">height=</span><span class="dv">1400</span>,<span class="at">units=</span><span class="st">"px"</span>)</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a><span class="fu">png_plot</span>(<span class="st">"monthly-locations"</span>,{<span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">3</span>,<span class="dv">4</span>),<span class="at">mar=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">3</span>,<span class="dv">1</span>));<span class="cf">for</span>(m <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">12</span>){</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a> <span class="fu">plot</span>(<span class="fu">st_geometry</span>(study),<span class="at">col=</span><span class="st">"#eee9dc"</span>,<span class="at">border=</span><span class="st">"#77776b"</span>,<span class="at">main=</span><span class="fu">paste</span>(month.abb[m],<span class="st">"|"</span>,monthly<span class="sc">$</span>count[m],<span class="st">"detections"</span>))</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a> <span class="fu">plot</span>(<span class="fu">st_geometry</span>(fire_sf[fire_sf<span class="sc">$</span>Month_num<span class="sc">==</span>m,]),<span class="at">add=</span><span class="cn">TRUE</span>,<span class="at">pch=</span><span class="dv">16</span>,<span class="at">cex=</span>.<span class="dv">4</span>,<span class="at">col=</span><span class="st">"#9b462d"</span>)}},<span class="dv">2000</span>,<span class="dv">1800</span>)</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>counts_plot <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(monthly,<span class="fu">aes</span>(<span class="fu">factor</span>(month_name,<span class="at">levels=</span>month.abb),count))<span class="sc">+</span></span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a> <span class="fu">geom_col</span>(<span class="at">fill=</span><span class="st">"#344b45"</span>,<span class="at">width=</span>.<span class="dv">65</span>)<span class="sc">+</span><span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label=</span>count),<span class="at">vjust=</span><span class="sc">-</span>.<span class="dv">4</span>,<span class="at">size=</span><span class="fl">3.5</span>)<span class="sc">+</span></span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a> <span class="fu">labs</span>(<span class="at">x=</span><span class="cn">NULL</span>,<span class="at">y=</span><span class="st">"Satellite detections"</span>,<span class="at">title=</span><span class="st">"A pronounced late-year concentration"</span>,<span class="at">subtitle=</span><span class="st">"Bangka main island | MODIS, January-December 2023"</span>)<span class="sc">+</span></span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a> <span class="fu">theme_minimal</span>(<span class="at">base_size=</span><span class="dv">13</span>)<span class="sc">+</span><span class="fu">theme</span>(<span class="at">panel.grid.major.x=</span><span class="fu">element_blank</span>())</span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a><span class="fu">ggsave</span>(<span class="fu">file.path</span>(base,<span class="st">"figures/monthly-counts.png"</span>),counts_plot,<span class="at">width=</span><span class="dv">10</span>,<span class="at">height=</span><span class="dv">5</span>,<span class="at">dpi=</span><span class="dv">180</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/fire-locations.png" class="img-fluid figure-img" alt="Map of Bangka island with 741 MODIS detection locations."></p>
<figcaption>MODIS detections within Bangka’s main-island boundary, projected in UTM zone 48S.</figcaption>
</figure>
</div>
<p><a href="figures/fire-locations.png">Download the location map (PNG)</a></p>
</section>
<section id="monthly-distribution" class="level3" data-number="5.2">
<h3 data-number="5.2" class="anchored" data-anchor-id="monthly-distribution"><span class="header-section-number">5.2</span> Monthly distribution</h3>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/monthly-locations.png" class="img-fluid figure-img" alt="Twelve monthly maps of detection locations on the same Bangka boundary."></p>
<figcaption>Monthly location panels with a common geographical extent, including low-count months.</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/monthly-counts.png" class="img-fluid figure-img" alt="Bar chart showing October as the peak month with 185 detections."></p>
<figcaption>Monthly counts of MODIS detections in 2023.</figcaption>
</figure>
</div>
<p>October records 185 detections, compared with only two in February. August–November together account for 75.8% of the annual total. That concentration is visible in the monthly panels, but the data alone do not explain its cause. Weather, land use, burning practices and observation conditions are plausible influences that would require additional evidence.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Month</th>
<th style="text-align: right;">Detections</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Jan</td>
<td style="text-align: right;">11</td>
</tr>
<tr class="even">
<td style="text-align: left;">Feb</td>
<td style="text-align: right;">2</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Mar</td>
<td style="text-align: right;">12</td>
</tr>
<tr class="even">
<td style="text-align: left;">Apr</td>
<td style="text-align: right;">9</td>
</tr>
<tr class="odd">
<td style="text-align: left;">May</td>
<td style="text-align: right;">21</td>
</tr>
<tr class="even">
<td style="text-align: left;">Jun</td>
<td style="text-align: right;">34</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Jul</td>
<td style="text-align: right;">79</td>
</tr>
<tr class="even">
<td style="text-align: left;">Aug</td>
<td style="text-align: right;">143</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Sep</td>
<td style="text-align: right;">146</td>
</tr>
<tr class="even">
<td style="text-align: left;">Oct</td>
<td style="text-align: right;">185</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Nov</td>
<td style="text-align: right;">88</td>
</tr>
<tr class="even">
<td style="text-align: left;">Dec</td>
<td style="text-align: right;">11</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
</section>
<section id="computing-space-time-kde-by-month" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="computing-space-time-kde-by-month"><span class="header-section-number">6</span> Computing space-time KDE by month</h2>
<p>A marked <code>ppp</code> combines projected locations with numerical month marks. Clipping it to the island window avoids treating the sea inside the bounding rectangle as observable land. <code>sparr::spattemp.density()</code> smooths both the spatial and temporal dimensions, with uniform spatial and temporal edge correction.</p>
<div class="cell">
<details class="code-fold">
<summary>Show R code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>month_kde <span class="ot">&lt;-</span> <span class="fu">cached</span>(<span class="st">"monthly"</span>,<span class="fu">spattemp.density</span>(month_ppp,<span class="at">verbose=</span><span class="cn">FALSE</span>))</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">png_plot</span>(<span class="st">"monthly-kde"</span>,{<span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">3</span>));<span class="cf">for</span>(m <span class="cf">in</span> <span class="dv">7</span><span class="sc">:</span><span class="dv">12</span>)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a> <span class="fu">plot</span>(month_kde,m,<span class="at">override.par=</span><span class="cn">FALSE</span>,<span class="at">fix.range=</span><span class="cn">TRUE</span>,<span class="at">main=</span><span class="fu">paste</span>(<span class="st">"Joint density |"</span>,month.abb[m]))},<span class="dv">2000</span>,<span class="dv">1400</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/monthly-kde.png" class="img-fluid figure-img" alt="Six joint-density maps for July through December, with a fixed shared density range."></p>
<figcaption>Joint space-time density estimates for July–December on a common scale.</figcaption>
</figure>
</div>
<p>These are <strong>joint probability-density</strong> surfaces, with units of 1/(m² × month), not counts per month. Multiplying by 741 would convert them to estimated event intensity under this model. The common colour range supports comparisons across panels. Month numbers are coarse time measurements: the default temporal selector may choose a very narrow bandwidth when many observations share an integer month. Such a result should not be interpreted as precise evidence about changes within a month.</p>
</section>
<section id="computing-kde-by-day-of-year" class="level2" data-number="7">
<h2 data-number="7" class="anchored" data-anchor-id="computing-kde-by-day-of-year"><span class="header-section-number">7</span> Computing KDE by day of year</h2>
<div class="cell">
<details class="code-fold">
<summary>Show R code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>day_kde <span class="ot">&lt;-</span> <span class="fu">cached</span>(<span class="st">"daily"</span>,<span class="fu">spattemp.density</span>(day_ppp,<span class="at">verbose=</span><span class="cn">FALSE</span>))</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>days <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">196</span>,<span class="dv">227</span>,<span class="dv">258</span>,<span class="dv">288</span>,<span class="dv">319</span>,<span class="dv">349</span>)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="fu">png_plot</span>(<span class="st">"daily-kde"</span>,{<span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">3</span>));<span class="cf">for</span>(d <span class="cf">in</span> days)</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a> <span class="fu">plot</span>(day_kde,d,<span class="at">override.par=</span><span class="cn">FALSE</span>,<span class="at">fix.range=</span><span class="cn">TRUE</span>,<span class="at">main=</span><span class="fu">paste</span>(<span class="st">"Joint density | day"</span>,d))},<span class="dv">2000</span>,<span class="dv">1400</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/daily-kde.png" class="img-fluid figure-img" alt="Default daily KDE slices at days 196, 227, 258, 288, 319 and 349."></p>
<figcaption>Default day-based KDE at six dates between July and December.</figcaption>
</figure>
</div>
<p>Day-of-year marks retain more timing information than month marks. The default spatial bandwidth is an oversmoothing choice, while the default temporal bandwidth uses the Sheather–Jones rule. Here the observed day range is 10–352. To reproduce the chapter’s KDE, its default temporal limits follow that observed range. This is different from saying that the actual observation campaign began and ended on those dates: the source covers the whole year.</p>
<p>The plotted slices use identical dates in the next comparison. Density units are now 1/(m² × day), so their numerical legends should not be compared directly with the month-based legend. A visually higher peak can reflect a narrower bandwidth rather than more underlying observations.</p>
</section>
<section id="improved-day-based-kde-bandwidth-selection" class="level2" data-number="8">
<h2 data-number="8" class="anchored" data-anchor-id="improved-day-based-kde-bandwidth-selection"><span class="header-section-number">8</span> Improved day-based KDE: bandwidth selection</h2>
<div class="cell">
<details class="code-fold">
<summary>Show R code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1234</span>)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>boot_bw <span class="ot">&lt;-</span> <span class="fu">cached</span>(<span class="st">"bootstrap"</span>,<span class="fu">BOOT.spattemp</span>(day_ppp,<span class="at">verbose=</span><span class="cn">TRUE</span>))</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>improved <span class="ot">&lt;-</span> <span class="fu">cached</span>(<span class="st">"improved"</span>,<span class="fu">spattemp.density</span>(day_ppp,<span class="at">h=</span>boot_bw[<span class="dv">1</span>],<span class="at">lambda=</span>boot_bw[<span class="dv">2</span>],<span class="at">verbose=</span><span class="cn">FALSE</span>))</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a><span class="fu">png_plot</span>(<span class="st">"improved-kde"</span>,{<span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">3</span>));<span class="cf">for</span>(d <span class="cf">in</span> days)</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a> <span class="fu">plot</span>(improved,d,<span class="at">override.par=</span><span class="cn">FALSE</span>,<span class="at">fix.range=</span><span class="cn">TRUE</span>,<span class="at">main=</span><span class="fu">paste</span>(<span class="st">"Bootstrap KDE | day"</span>,d))},<span class="dv">2000</span>,<span class="dv">1400</span>)</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>bandwidths <span class="ot">&lt;-</span> <span class="fu">tibble</span>(<span class="at">method=</span><span class="fu">c</span>(<span class="st">"Month defaults"</span>,<span class="st">"Day defaults"</span>,<span class="st">"Bootstrap day"</span>),</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a> <span class="at">spatial_m=</span><span class="fu">c</span>(month_kde<span class="sc">$</span>h,day_kde<span class="sc">$</span>h,improved<span class="sc">$</span>h),<span class="at">temporal=</span><span class="fu">c</span>(month_kde<span class="sc">$</span>lambda,day_kde<span class="sc">$</span>lambda,improved<span class="sc">$</span>lambda),<span class="at">time_unit=</span><span class="fu">c</span>(<span class="st">"month"</span>,<span class="st">"day"</span>,<span class="st">"day"</span>))</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a><span class="fu">write_csv</span>(bandwidths,<span class="fu">file.path</span>(base,<span class="st">"outputs/bandwidths.csv"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p><code>BOOT.spattemp()</code> jointly selects spatial and temporal bandwidths by minimising a bootstrap approximation to integrated squared error. Despite its name, the implementation exploits Gaussian-kernel theory and does not require repeatedly resampling the observations. The seed is fixed for reproducibility. I use the returned bandwidths directly rather than substituting the workbook’s rounded 9,000 m and 19-day settings.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Method</th>
<th style="text-align: right;">Spatial bandwidth (m)</th>
<th style="text-align: right;">Temporal bandwidth</th>
<th style="text-align: left;">Time unit</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Month defaults</td>
<td style="text-align: right;">15102.469</td>
<td style="text-align: right;">0.030</td>
<td style="text-align: left;">month</td>
</tr>
<tr class="even">
<td style="text-align: left;">Day defaults</td>
<td style="text-align: right;">15102.469</td>
<td style="text-align: right;">6.320</td>
<td style="text-align: left;">day</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Bootstrap day</td>
<td style="text-align: right;">9105.736</td>
<td style="text-align: right;">18.858</td>
<td style="text-align: left;">day</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/improved-kde.png" class="img-fluid figure-img" alt="Six daily KDE slices computed with bootstrap-selected space and time bandwidths."></p>
<figcaption>Daily density estimates using the jointly selected bandwidths, on a common scale.</figcaption>
</figure>
</div>
<p><a href="figures/improved-kde.png">Download the comparison figure (PNG)</a></p>
<p>The July and August slices show a prominent north-western concentration. By October, stronger density is visible in the southern part of the island, while the November slice retains a more localised south-eastern concentration. December is subdued on the same colour scale. This changing geography is information that an annual point map and a monthly total cannot show separately. It describes a shift in the distribution of observations, not the movement of one fire across the island.</p>
<p>The selected spatial bandwidth is 9106 m, compared with 1.5102^{4} m under the default rule; the temporal bandwidth is 18.86 days, compared with 6.32. This changes the balance between spatial detail and temporal continuity. “Improved” refers to the bandwidth-selection criterion, not proof that the estimated surface equals the true fire process.</p>
<section id="watching-the-pattern-change" class="level3" data-number="8.1">
<h3 data-number="8.1" class="anchored" data-anchor-id="watching-the-pattern-change"><span class="header-section-number">8.1</span> Watching the pattern change</h3>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/daily-kde.gif" class="img-fluid figure-img" alt="Animation of the bootstrap KDE through the observed dates of 2023."></p>
<figcaption>Weekly frames sampled from the full daily KDE, with a common density scale.</figcaption>
</figure>
</div>
<p>The animation samples every seven days from the daily estimate to keep the page manageable. The analysis still evaluates every integer day in the observed interval; the animation is a display choice, not a change in the underlying data. <a href="figures/daily-kde.gif">Download animation</a>.</p>
</section>
</section>
<section id="space-time-point-pattern-analysis-with-stpp" class="level2" data-number="9">
<h2 data-number="9" class="anchored" data-anchor-id="space-time-point-pattern-analysis-with-stpp"><span class="header-section-number">9</span> Space-time point-pattern analysis with stpp</h2>
<section id="preparing-the-space-time-object" class="level3" data-number="9.1">
<h3 data-number="9.1" class="anchored" data-anchor-id="preparing-the-space-time-object"><span class="header-section-number">9.1</span> Preparing the space-time object</h3>
<p><code>as.3dpoints()</code> combines x, y and integer day-of-year into a space-time point-pattern object. Dates are kept at daily precision rather than inventing an ordering within a day. This is particularly important when interpreting the <code>infectious=TRUE</code> setting, which considers future-event neighbourhoods: it is a computational definition, not evidence that one fire transmitted to another.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/space-time-points.png" class="img-fluid figure-img" alt="Spatial locations alongside the cumulative count of 741 detections by day of year."></p>
<figcaption>Spatial locations and cumulative detections through the year; x and y are projected metres, and t is day of year.</figcaption>
</figure>
</div>
</section>
<section id="computing-the-space-time-k-function" class="level3" data-number="9.2">
<h3 data-number="9.2" class="anchored" data-anchor-id="computing-the-space-time-k-function"><span class="header-section-number">9.2</span> Computing the space-time K-function</h3>
<div class="cell">
<details class="code-fold">
<summary>Show R code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Use the observed study polygon, simplified only for expensive pairwise edge weights.</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="co"># A 100 m coastal buffer avoids clipping near-coast points after simplification.</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>k_region <span class="ot">&lt;-</span> <span class="fu">st_simplify</span>(<span class="fu">st_buffer</span>(study,<span class="dv">100</span>),<span class="at">dTolerance=</span><span class="dv">100</span>)</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(<span class="fu">all</span>(<span class="fu">lengths</span>(<span class="fu">st_intersects</span>(fire_sf,k_region))<span class="sc">&gt;</span><span class="dv">0</span>))</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>ring <span class="ot">&lt;-</span> <span class="fu">st_geometry</span>(k_region)[[<span class="dv">1</span>]][[<span class="dv">1</span>]]</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>k_region <span class="ot">&lt;-</span> <span class="fu">st_sfc</span>(<span class="fu">st_polygon</span>(<span class="fu">list</span>(ring)),<span class="at">crs=</span><span class="dv">32748</span>)</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(<span class="fu">is.matrix</span>(ring),<span class="fu">ncol</span>(ring)<span class="sc">==</span><span class="dv">2</span>)</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>fire_stpp <span class="ot">&lt;-</span> <span class="fu">as.3dpoints</span>(<span class="fu">data.frame</span>(<span class="at">x=</span>coords[,<span class="dv">1</span>],<span class="at">y=</span>coords[,<span class="dv">2</span>],<span class="at">t=</span><span class="fu">as.integer</span>(fire_sf<span class="sc">$</span>DayofYear)))</span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a><span class="fu">png_plot</span>(<span class="st">"space-time-points"</span>,{<span class="fu">plot</span>(fire_stpp,ring,<span class="at">pch=</span><span class="dv">19</span>,<span class="at">mark=</span><span class="cn">FALSE</span>)})</span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a><span class="co"># The whole 2023 interval must contain all observations; c(150,250) does not.</span></span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a>stik <span class="ot">&lt;-</span> <span class="fu">cached</span>(<span class="st">"stik"</span>,<span class="fu">STIKhat</span>(fire_stpp,<span class="at">s.region=</span>ring,<span class="at">t.region=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">365</span>),</span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a> <span class="at">dist=</span><span class="fu">seq</span>(<span class="dv">1000</span>,<span class="dv">30000</span>,<span class="at">by=</span><span class="dv">1000</span>),<span class="at">times=</span><span class="fu">seq</span>(<span class="dv">1</span>,<span class="dv">60</span>,<span class="at">by=</span><span class="dv">2</span>),<span class="at">infectious=</span><span class="cn">TRUE</span>))</span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a><span class="co"># plotK manages its own graphics device; supply a file device explicitly.</span></span>
<span id="cb6-14"><a href="#cb6-14" aria-hidden="true" tabindex="-1"></a>saved_device <span class="ot">&lt;-</span> <span class="fu">options</span>(<span class="at">device=</span><span class="cf">function</span>(...) <span class="fu">png</span>(<span class="fu">file.path</span>(base,<span class="st">"figures/workbook-k-contour.png"</span>),<span class="at">width=</span><span class="dv">1800</span>,<span class="at">height=</span><span class="dv">1200</span>,<span class="at">res=</span><span class="dv">150</span>))</span>
<span id="cb6-15"><a href="#cb6-15" aria-hidden="true" tabindex="-1"></a><span class="fu">plotK</span>(stik,<span class="at">n=</span><span class="dv">20</span>,<span class="at">L=</span><span class="cn">TRUE</span>,<span class="at">type=</span><span class="st">"contour"</span>,<span class="at">main=</span><span class="st">"Centred space-time K"</span>)</span>
<span id="cb6-16"><a href="#cb6-16" aria-hidden="true" tabindex="-1"></a><span class="fu">dev.off</span>();<span class="fu">options</span>(saved_device)</span>
<span id="cb6-17"><a href="#cb6-17" aria-hidden="true" tabindex="-1"></a>ratio <span class="ot">&lt;-</span> stik<span class="sc">$</span>Khat<span class="sc">/</span>stik<span class="sc">$</span>Ktheo</span>
<span id="cb6-18"><a href="#cb6-18" aria-hidden="true" tabindex="-1"></a>k_display <span class="ot">&lt;-</span> <span class="fu">expand.grid</span>(<span class="at">spatial_km=</span>stik<span class="sc">$</span>dist<span class="sc">/</span><span class="dv">1000</span>,<span class="at">lag_days=</span>stik<span class="sc">$</span>times)</span>
<span id="cb6-19"><a href="#cb6-19" aria-hidden="true" tabindex="-1"></a>k_display<span class="sc">$</span>excess <span class="ot">&lt;-</span> <span class="fu">as.vector</span>(stik<span class="sc">$</span>Khat<span class="sc">-</span>stik<span class="sc">$</span>Ktheo)<span class="sc">/</span><span class="fl">1e6</span></span>
<span id="cb6-20"><a href="#cb6-20" aria-hidden="true" tabindex="-1"></a>k_plot <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(k_display,<span class="fu">aes</span>(spatial_km,lag_days))<span class="sc">+</span></span>
<span id="cb6-21"><a href="#cb6-21" aria-hidden="true" tabindex="-1"></a> <span class="fu">geom_raster</span>(<span class="fu">aes</span>(<span class="at">fill=</span>excess))<span class="sc">+</span><span class="fu">geom_contour</span>(<span class="fu">aes</span>(<span class="at">z=</span>excess),<span class="at">colour=</span><span class="st">"#273d34"</span>,<span class="at">bins=</span><span class="dv">8</span>,<span class="at">linewidth=</span>.<span class="dv">3</span>)<span class="sc">+</span></span>
<span id="cb6-22"><a href="#cb6-22" aria-hidden="true" tabindex="-1"></a> <span class="fu">scale_fill_gradient</span>(<span class="at">low=</span><span class="st">"#faf7ee"</span>,<span class="at">high=</span><span class="st">"#49675a"</span>,<span class="at">name=</span><span class="st">"K excess</span><span class="sc">\n</span><span class="st">(km^2 days)"</span>)<span class="sc">+</span></span>
<span id="cb6-23"><a href="#cb6-23" aria-hidden="true" tabindex="-1"></a> <span class="fu">labs</span>(<span class="at">x=</span><span class="st">"Spatial distance u (km)"</span>,<span class="at">y=</span><span class="st">"Temporal lag v (days)"</span>,<span class="at">title=</span><span class="st">"More space-time neighbours than a uniform reference"</span>,</span>
<span id="cb6-24"><a href="#cb6-24" aria-hidden="true" tabindex="-1"></a> <span class="at">subtitle=</span><span class="st">"Estimated K minus pi*u^2*v | isotropic edge correction"</span>,</span>
<span id="cb6-25"><a href="#cb6-25" aria-hidden="true" tabindex="-1"></a> <span class="at">caption=</span><span class="st">"Descriptive departure, not a significance test | Bangka MODIS detections, 2023"</span>)<span class="sc">+</span></span>
<span id="cb6-26"><a href="#cb6-26" aria-hidden="true" tabindex="-1"></a> <span class="fu">theme_minimal</span>(<span class="at">base_size=</span><span class="dv">13</span>)<span class="sc">+</span><span class="fu">theme</span>(<span class="at">panel.grid=</span><span class="fu">element_blank</span>())</span>
<span id="cb6-27"><a href="#cb6-27" aria-hidden="true" tabindex="-1"></a><span class="fu">ggsave</span>(<span class="fu">file.path</span>(base,<span class="st">"figures/space-time-k.png"</span>),k_plot,<span class="at">width=</span><span class="dv">10</span>,<span class="at">height=</span><span class="fl">6.5</span>,<span class="at">dpi=</span><span class="dv">180</span>)</span>
<span id="cb6-28"><a href="#cb6-28" aria-hidden="true" tabindex="-1"></a><span class="fu">write_csv</span>(<span class="fu">as.data.frame</span>(<span class="fu">as.table</span>(ratio)) <span class="sc">|&gt;</span> <span class="fu">mutate</span>(<span class="at">spatial_m=</span><span class="fu">rep</span>(stik<span class="sc">$</span>dist,<span class="fu">length</span>(stik<span class="sc">$</span>times)),<span class="at">lag_days=</span><span class="fu">rep</span>(stik<span class="sc">$</span>times,<span class="at">each=</span><span class="fu">length</span>(stik<span class="sc">$</span>dist))) <span class="sc">|&gt;</span> <span class="fu">select</span>(spatial_m,lag_days,<span class="at">ratio=</span>Freq),<span class="fu">file.path</span>(base,<span class="st">"outputs/k-ratio.csv"</span>))</span>
<span id="cb6-29"><a href="#cb6-29" aria-hidden="true" tabindex="-1"></a>k_audit <span class="ot">&lt;-</span> <span class="fu">tibble</span>(<span class="at">original_area_km2=</span><span class="fu">as.numeric</span>(<span class="fu">st_area</span>(study))<span class="sc">/</span><span class="fl">1e6</span>,<span class="at">k_area_km2=</span><span class="fu">as.numeric</span>(<span class="fu">st_area</span>(k_region))<span class="sc">/</span><span class="fl">1e6</span>,</span>
<span id="cb6-30"><a href="#cb6-30" aria-hidden="true" tabindex="-1"></a> <span class="at">area_change_percent=</span><span class="dv">100</span><span class="sc">*</span>(<span class="fu">as.numeric</span>(<span class="fu">st_area</span>(k_region))<span class="sc">/</span><span class="fu">as.numeric</span>(<span class="fu">st_area</span>(study))<span class="sc">-</span><span class="dv">1</span>),<span class="at">vertices=</span><span class="fu">nrow</span>(ring),<span class="at">retained=</span><span class="fu">nrow</span>(fire_stpp))</span>
<span id="cb6-31"><a href="#cb6-31" aria-hidden="true" tabindex="-1"></a><span class="fu">write_csv</span>(k_audit,<span class="fu">file.path</span>(base,<span class="st">"outputs/k-window.csv"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p>I use the full year, <code>t.region=c(1,365)</code>. The chapter’s example of <code>c(150,250)</code> does not contain all the observations and cannot represent this full-year analysis. The spatial window for pairwise edge correction uses a documented coastal approximation: a 100-metre buffer followed by 100-metre simplification, retaining its exterior ring. All 741 points must remain inside it. This keeps the pairwise calculation tractable; the KDEs retain the original detailed island window. The resulting area difference is reported below, and coastal results remain sensitive to this approximation.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 26%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 11%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">Original area (km^2)</th>
<th style="text-align: right;">K window (km^2)</th>
<th style="text-align: right;">Area change (%)</th>
<th style="text-align: right;">Vertices</th>
<th style="text-align: right;">Retained points</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">11533.63</td>
<td style="text-align: right;">11627.75</td>
<td style="text-align: right;">0.816</td>
<td style="text-align: right;">903</td>
<td style="text-align: right;">741</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The <code>STIKhat</code> name can be misleading here: <strong>without a supplied <code>lambda</code> vector, the function uses a constant-intensity estimate</strong>. This reproduces the chapter’s homogeneous-reference calculation; it is not an intensity-adjusted test. I evaluate spatial distances of 1–30 km and temporal lags of 1–59 days, with isotropic edge correction.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/space-time-k.png" class="img-fluid figure-img" alt="Contour plot of estimated space-time K minus its homogeneous Poisson reference."></p>
<figcaption>Centred space-time K surface using the future-event convention.</figcaption>
</figure>
</div>
<p>The labelled display converts spatial distances to kilometres and the centred K values to km²-days for readability; it does not change the calculation. The <a href="figures/workbook-k-contour.png">workbook-style contour output</a> is also available.</p>
</section>
<section id="interpreting-the-surface" class="level3" data-number="9.3">
<h3 data-number="9.3" class="anchored" data-anchor-id="interpreting-the-surface"><span class="header-section-number">9.3</span> Interpreting the surface</h3>
<p>For the future-event convention, the reference is <span class="math inline">\(\pi u^2v\)</span>, where u is spatial distance and v is temporal lag. In the installed <code>stpp</code> implementation, <code>plotK(L=TRUE)</code> displays <span class="math inline">\(\widehat K(u,v)-\pi u^2v\)</span>; it is <strong>not</strong> the square-root L transformation used in the previous spatial-only exercise. Positive contours indicate more space-time neighbours than the homogeneous Poisson reference at that combination of scales.</p>
<p>Across the evaluated grid, the observed/reference ratio ranges from 2.56 to 255.18. These are descriptive ratios, not p-values. The <a href="outputs/k-ratio.csv">numeric ratio surface</a> makes the comparison inspectable. Strong seasonality and spatially uneven intensity can produce departures even without causal interaction between distinct fires. No simulation envelope or global independence test is computed in this chapter workflow, so I do not label the contours statistically significant.</p>
</section>
</section>
<section id="what-i-learned" class="level2" data-number="10">
<h2 data-number="10" class="anchored" data-anchor-id="what-i-learned"><span class="header-section-number">10</span> What I learned</h2>
<p>The count chart and density maps answer different questions. October’s high count is a direct description of the records. A bright KDE peak also depends on how much smoothing has been applied across space and time. Comparing the selected bandwidths made that distinction concrete.</p>
<p>The study window is part of the analysis, not simply a map background. The workbook’s province label initially suggests a larger region than its example actually uses. Matching the 297 subdistricts and 741 observations required checking the geographical extent, not just the filename. Time needs the same care: a K-function window must contain the events being analysed.</p>
<p>Finally, a satellite detection is not the same thing as an independent incident. Neither a concentration of detections nor a positive K departure proves that fires caused neighbouring fires. A stronger investigation would combine observation conditions and land cover with a spatially and temporally varying intensity model, then use simulation-based inference and bandwidth/window sensitivity checks. The present results identify patterns worth investigating; they do not establish causes or quantify financial losses.</p>
</section>
<section id="reproducibility-and-references" class="level2" data-number="11">
<h2 data-number="11" class="anchored" data-anchor-id="reproducibility-and-references"><span class="header-section-number">11</span> Reproducibility and references</h2>
<ul>
<li><a href="https://r4gdsa.netlify.app/chap06">Workbook Chapter 6</a>, accessed 18 September 2026.</li>
<li><a href="https://firms.modaps.eosdis.nasa.gov/">NASA FIRMS</a>, MODIS Collection 6.1, 2023 country archive.</li>
<li><a href="https://tilmandavies.github.io/sparr/reference/spattemp.density.html">sparr density documentation</a> and <a href="https://tilmandavies.github.io/sparr/reference/BOOT.spattemp.html">bootstrap selector</a>.</li>
<li><a href="https://cran.r-project.org/web/packages/stpp/stpp.pdf">stpp package documentation</a>.</li>
<li><a href="https://github.com/yufanyou2025/ISS626-VAA/tree/master/Hands-on_Ex/Hands-on_Ex03">Source project</a>, <a href="outputs/data-manifest.csv">download manifest</a>, <a href="outputs/audit.csv">validation audit</a>, and <a href="outputs/monthly-counts.csv">monthly counts</a>.</li>
</ul>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>